import { Injectable, NotFoundException } from '@nestjs/common';
import { DatabaseService } from '../database/database.service';
import { CreateAttendanceDto, UpdateAttendanceDto, BulkAttendanceDto } from './attendance.dto';
@Injectable()
export class AttendanceService {
  constructor(private db: DatabaseService) {}
  calcHours(ci: string, co: string) { const [ih,im]=ci.split(':').map(Number); const [oh,om]=co.split(':').map(Number); return Math.round(((oh*60+om)-(ih*60+im))/60*100)/100; }
  async findAll(employeeId?: string, from?: string, to?: string) { let q='SELECT a.*,e.first_name,e.last_name FROM attendance a JOIN employees e ON e.id=a.employee_id'; const p: any[]=[]; if(employeeId){q+=' WHERE a.employee_id=$1';p.push(employeeId);} if(from&&to){q+=employeeId?' AND':' WHERE';q+=' a.date BETWEEN $'+(p.length+1)+' AND $'+(p.length+2);p.push(from,to);} q+=' ORDER BY a.date DESC'; return (await this.db.query(q,p)).rows; }
  async findByDate(date: string) { return (await this.db.query('SELECT a.*,e.first_name,e.last_name FROM attendance a JOIN employees e ON e.id=a.employee_id WHERE a.date=$1',[date])).rows; }
  async findOne(id: string) { const r=await this.db.query('SELECT * FROM attendance WHERE id=$1',[id]); if(!r.rows[0]) throw new NotFoundException('Not found'); return r.rows[0]; }
  async create(dto: CreateAttendanceDto) { let wh=dto.workHours??null; if(dto.checkIn&&dto.checkOut&&!wh) wh=this.calcHours(dto.checkIn,dto.checkOut); return (await this.db.query('INSERT INTO attendance(employee_id,date,check_in,check_out,work_hours,status,notes) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[dto.employeeId,dto.date,dto.checkIn??null,dto.checkOut??null,wh,dto.status??'present',dto.notes??null])).rows[0]; }
  async bulkCreate(dto: BulkAttendanceDto) { const results=[]; for(const r of dto.records){ results.push((await this.db.query('INSERT INTO attendance(employee_id,date,check_in,check_out,status) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING RETURNING *',[r.employeeId,dto.date,r.checkIn??null,r.checkOut??null,r.status])).rows[0]); } return results.filter(Boolean); }
  async update(id: string, dto: UpdateAttendanceDto) { const ex=await this.findOne(id); let wh=dto.workHours??null; const ci=dto.checkIn??ex.check_in; const co=dto.checkOut??ex.check_out; if(ci&&co&&!wh) wh=this.calcHours(ci,co); return (await this.db.query('UPDATE attendance SET check_in=COALESCE($1,check_in),check_out=COALESCE($2,check_out),work_hours=COALESCE($3,work_hours),status=COALESCE($4,status),notes=COALESCE($5,notes),updated_at=NOW() WHERE id=$6 RETURNING *',[dto.checkIn??null,dto.checkOut??null,wh,dto.status??null,dto.notes??null,id])).rows[0]; }
  async remove(id: string) { await this.findOne(id); await this.db.query('DELETE FROM attendance WHERE id=$1',[id]); return {message:'Deleted'}; }
  async getMonthSummary(employeeId: string, year: number, month: number) { const from=`${year}-${String(month).padStart(2,'0')}-01`; const to=`${year}-${String(month).padStart(2,'0')}-${new Date(year,month,0).getDate()}`; const rows=(await this.db.query('SELECT * FROM attendance WHERE employee_id=$1 AND date BETWEEN $2 AND $3',[employeeId,from,to])).rows; const s={present:0,absent:0,late:0,halfDay:0,onLeave:0,totalHours:0}; rows.forEach((r:any)=>{if(r.status==='present')s.present++;else if(r.status==='absent')s.absent++;else if(r.status==='late')s.late++;else if(r.status==='half_day')s.halfDay++;else if(r.status==='on_leave')s.onLeave++;s.totalHours+=Number(r.work_hours||0);}); return {employeeId,year,month,...s,records:rows}; }
}
