import {BadRequestException,ForbiddenException,Injectable,NotFoundException,OnModuleInit} from '@nestjs/common';
import {DatabaseService} from '../database/database.service';
import {EmployeesService} from './employees.service';
@Injectable()
export class HrManagementService implements OnModuleInit{
 constructor(private db:DatabaseService,private es:EmployeesService){}
 async onModuleInit(){await this.db.query(`CREATE EXTENSION IF NOT EXISTS pgcrypto;
 CREATE TABLE IF NOT EXISTS hr_employee_profiles(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL,employee_id uuid UNIQUE NOT NULL,branch_id uuid,profile jsonb DEFAULT '{}',created_at timestamptz DEFAULT NOW(),updated_at timestamptz DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS hr_attendance_records(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL,branch_id uuid,employee_id uuid NOT NULL,work_date date NOT NULL,status varchar(30) DEFAULT 'present',check_in time,check_out time,break_minutes int DEFAULT 0,late_minutes int DEFAULT 0,early_exit_minutes int DEFAULT 0,notes text,created_by uuid,created_at timestamptz DEFAULT NOW(),updated_at timestamptz DEFAULT NOW(),UNIQUE(company_id,employee_id,work_date));
 CREATE TABLE IF NOT EXISTS hr_shifts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL,name varchar(120),start_time time,end_time time,break_minutes int DEFAULT 0,weekly_off jsonb DEFAULT '[]',is_active boolean DEFAULT true,created_at timestamptz DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS hr_shift_assignments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL,shift_id uuid,employee_id uuid,start_date date,end_date date,created_at timestamptz DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS hr_leave_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL,branch_id uuid,employee_id uuid,leave_type varchar(40),start_date date,end_date date,total_days numeric(8,2),reason text,attachment_url text,status varchar(30) DEFAULT 'pending',review_comment text,reviewed_by uuid,reviewed_at timestamptz,created_at timestamptz DEFAULT NOW(),updated_at timestamptz DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS hr_payroll_records(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL,branch_id uuid,employee_id uuid,period_month int,period_year int,basic_salary numeric(14,2) DEFAULT 0,allowances numeric(14,2) DEFAULT 0,overtime numeric(14,2) DEFAULT 0,commission numeric(14,2) DEFAULT 0,bonus numeric(14,2) DEFAULT 0,deductions numeric(14,2) DEFAULT 0,net_salary numeric(14,2) DEFAULT 0,status varchar(30) DEFAULT 'draft',paid_at timestamptz,payment_reference text,created_at timestamptz DEFAULT NOW(),UNIQUE(company_id,employee_id,period_month,period_year));
 CREATE TABLE IF NOT EXISTS hr_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL,branch_id uuid,employee_id uuid,type varchar(60),subject varchar(200),details text,attachment_url text,data jsonb DEFAULT '{}',status varchar(30) DEFAULT 'pending',comment text,reviewed_by uuid,reviewed_at timestamptz,created_at timestamptz DEFAULT NOW(),updated_at timestamptz DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS hr_documents(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL,branch_id uuid,employee_id uuid,document_type varchar(60),document_number varchar(150),issue_date date,expiry_date date,attachment_url text,status varchar(30) DEFAULT 'valid',created_at timestamptz DEFAULT NOW(),updated_at timestamptz DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS hr_activity_logs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL,branch_id uuid,user_id uuid,employee_id uuid,action varchar(100),entity_type varchar(60),entity_id uuid,details jsonb DEFAULT '{}',created_at timestamptz DEFAULT NOW());`)}
 private p(u:any){return Array.isArray(u?.permissions)?u.permissions:[]} private can(u:any,...n:string[]){const p=this.p(u);return p.includes('*')||n.some(y=>p.some((x:string)=>x===y||(x.endsWith('.*')&&y.startsWith(x.slice(0,-1)))))||String(u?.role||'').toLowerCase().includes('admin')} private need(u:any,...n:string[]){if(!this.can(u,...n))throw new ForbiddenException('HR permission required')} private br(u:any,b?:string){return u.branchId||b||null}
 private async log(u:any,a:string,t:string,id?:string,e?:string,d:any={}){await this.db.query(`INSERT INTO hr_activity_logs(company_id,branch_id,user_id,employee_id,action,entity_type,entity_id,details) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[u.companyId,u.branchId||null,u.sub||null,e||null,a,t,id||null,JSON.stringify(d)])}
 private name=`COALESCE(NULLIF(to_jsonb(e)->>'full_name',''),TRIM(CONCAT(to_jsonb(e)->>'first_name',' ',to_jsonb(e)->>'last_name')))`;
 async employees(u:any,q:any={}){this.need(u,'hr.view','hr.employees.view','hr.self.view');const b=this.br(u,q.branchId),s=String(q.search||''),self=this.can(u,'hr.self.view')&&!this.can(u,'hr.employees.view','hr.*');const r=await this.db.query(`SELECT e.id,${this.name} full_name,COALESCE(to_jsonb(e)->>'employee_number',to_jsonb(e)->>'employee_id') employee_number,COALESCE(to_jsonb(e)->>'phone','') mobile_number,COALESCE(to_jsonb(e)->>'email','') email,COALESCE(to_jsonb(e)->>'job_title','') job_title,COALESCE(to_jsonb(e)->>'hire_date',to_jsonb(e)->>'joining_date') joining_date,COALESCE(to_jsonb(e)->>'status','active') status,hp.branch_id,hp.profile,b.name branch_name,d.name department_name FROM employees e LEFT JOIN hr_employee_profiles hp ON hp.employee_id=e.id LEFT JOIN branches b ON b.id=hp.branch_id LEFT JOIN departments d ON d.id=NULLIF(COALESCE(to_jsonb(e)->>'department_id',hp.profile->>'department_id'),'')::uuid WHERE COALESCE(to_jsonb(e)->>'company_id',$1::text)=$1::text AND ($2::uuid IS NULL OR hp.branch_id=$2) AND ($3='' OR ${this.name} ILIKE $4) AND ($5=false OR LOWER(COALESCE(to_jsonb(e)->>'email',''))=LOWER($6)) ORDER BY e.created_at DESC`,[u.companyId,b,s,`%${s}%`,self,u.email||'']);return r.rows.map((x:any)=>({...x,...x.profile,profile:undefined}))}
 async employee(u:any,id:string){const e=(await this.employees(u,{})).find((x:any)=>x.id===id);if(!e)throw new NotFoundException('Employee not found');if(!this.can(u,'hr.salary.view','payroll.view'))for(const k of ['basic_salary','housing_allowance','transport_allowance','other_allowance','iban'])delete e[k];return e}
 async createEmployee(u:any,b:any){this.need(u,'hr.employees.manage');const e=await this.es.create(u.companyId,{...b,phone:b.mobile_number,hire_date:b.joining_date||b.hire_date});await this.db.query(`INSERT INTO hr_employee_profiles(company_id,employee_id,branch_id,profile) VALUES($1,$2,$3,$4) ON CONFLICT(employee_id) DO UPDATE SET branch_id=EXCLUDED.branch_id,profile=EXCLUDED.profile,updated_at=NOW()`,[u.companyId,e.id,b.branch_id||null,JSON.stringify(b)]);await this.docsFromProfile(u,e.id,b);await this.log(u,'employee.created','employee',e.id,e.id);return this.employee(u,e.id)}
 async updateEmployee(u:any,id:string,b:any){this.need(u,'hr.employees.manage');await this.es.update(u.companyId,id,{...b,phone:b.mobile_number,hire_date:b.joining_date||b.hire_date});const old=await this.db.query(`SELECT profile FROM hr_employee_profiles WHERE employee_id=$1`,[id]),p={...(old.rows[0]?.profile||{}),...b};await this.db.query(`INSERT INTO hr_employee_profiles(company_id,employee_id,branch_id,profile) VALUES($1,$2,$3,$4) ON CONFLICT(employee_id) DO UPDATE SET branch_id=EXCLUDED.branch_id,profile=EXCLUDED.profile,updated_at=NOW()`,[u.companyId,id,b.branch_id||p.branch_id||null,JSON.stringify(p)]);await this.log(u,'employee.updated','employee',id,id,{fields:Object.keys(b)});return this.employee(u,id)}
 async employeeStatus(u:any,id:string,s:string){this.need(u,'hr.employees.manage');if(!['active','inactive','terminated'].includes(s))throw new BadRequestException('Invalid status');await this.es.update(u.companyId,id,{status:s});await this.log(u,'employee.'+s,'employee',id,id);return{success:true,status:s}}
 private async docsFromProfile(u:any,id:string,b:any){for(const [t,n,x,a] of [['iqama',b.iqama_number,b.iqama_expiry_date,b.iqama_attachment],['passport',b.passport_number,b.passport_expiry_date,b.passport_attachment],['work_permit','',b.work_permit_expiry_date,b.work_permit_attachment],['medical_insurance','',b.medical_insurance_expiry_date,b.medical_insurance_attachment],['employment_contract','',b.contract_end_date,b.contract_attachment],['iban_certificate',b.iban,'',b.iban_attachment]])if(n||x||a)await this.db.query(`INSERT INTO hr_documents(company_id,branch_id,employee_id,document_type,document_number,expiry_date,attachment_url) VALUES($1,$2,$3,$4,$5,$6,$7)`,[u.companyId,b.branch_id||null,id,t,n||null,x||null,a||null])}
 async dashboard(u:any,b?:string){this.need(u,'hr.view','hr.dashboard');const br=this.br(u,b),[e,a,l,d,c]=await Promise.all([this.db.query(`SELECT COUNT(*) n FROM employees e LEFT JOIN hr_employee_profiles hp ON hp.employee_id=e.id WHERE COALESCE(to_jsonb(e)->>'company_id',$1::text)=$1::text AND ($2::uuid IS NULL OR hp.branch_id=$2) AND COALESCE(to_jsonb(e)->>'status','active')='active'`,[u.companyId,br]),this.db.query(`SELECT COUNT(*) FILTER(WHERE status IN('present','late')) p,COUNT(*) FILTER(WHERE status='absent') a FROM hr_attendance_records WHERE company_id=$1 AND work_date=CURRENT_DATE AND ($2::uuid IS NULL OR branch_id=$2)`,[u.companyId,br]),this.db.query(`SELECT COUNT(*) FILTER(WHERE status='approved' AND CURRENT_DATE BETWEEN start_date AND end_date) o,COUNT(*) FILTER(WHERE status='pending') p FROM hr_leave_requests WHERE company_id=$1 AND ($2::uuid IS NULL OR branch_id=$2)`,[u.companyId,br]),this.db.query(`SELECT COUNT(*) FILTER(WHERE document_type='iqama' AND expiry_date<=CURRENT_DATE+90) i,COUNT(*) FILTER(WHERE document_type='passport' AND expiry_date<=CURRENT_DATE+90) p FROM hr_documents WHERE company_id=$1 AND expiry_date>=CURRENT_DATE AND ($2::uuid IS NULL OR branch_id=$2)`,[u.companyId,br]),this.db.query(`SELECT COUNT(*) n FROM hr_employee_profiles WHERE company_id=$1 AND NULLIF(profile->>'contract_end_date','')::date BETWEEN CURRENT_DATE AND CURRENT_DATE+90`,[u.companyId])]);return{totalEmployees:+e.rows[0].n,presentToday:+(a.rows[0].p||0),absentToday:+(a.rows[0].a||0),onLeave:+(l.rows[0].o||0),pendingLeaves:+(l.rows[0].p||0),expiringIqama:+(d.rows[0].i||0),expiringPassport:+(d.rows[0].p||0),expiringContract:+(c.rows[0].n||0)}}
 async attendance(u:any,q:any){this.need(u,'hr.attendance.view');return(await this.db.query(`SELECT a.*,${this.name} employee_name FROM hr_attendance_records a JOIN employees e ON e.id=a.employee_id WHERE a.company_id=$1 AND ($2::uuid IS NULL OR a.branch_id=$2) AND ($3::date IS NULL OR a.work_date=$3) AND ($4='' OR a.status=$4) ORDER BY a.work_date DESC,employee_name`,[u.companyId,this.br(u,q.branchId),q.date||null,q.status||''])).rows}
 async recordAttendance(u:any,b:any){this.need(u,'hr.attendance.manage');const out=[];for(const x of (b.records||[b])){const r=await this.db.query(`INSERT INTO hr_attendance_records(company_id,branch_id,employee_id,work_date,status,check_in,check_out,break_minutes,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(company_id,employee_id,work_date) DO UPDATE SET status=EXCLUDED.status,check_in=EXCLUDED.check_in,check_out=EXCLUDED.check_out,break_minutes=EXCLUDED.break_minutes,notes=EXCLUDED.notes,updated_at=NOW() RETURNING *`,[u.companyId,x.branch_id||u.branchId||null,x.employee_id,x.work_date||b.work_date,x.status||'present',x.check_in||null,x.check_out||null,+x.break_minutes||0,x.notes||null,u.sub||null]);out.push(r.rows[0])}await this.log(u,'attendance.recorded','attendance');return out}
 async shifts(u:any){this.need(u,'hr.shifts.view','hr.attendance.view');return(await this.db.query(`SELECT s.*,COUNT(a.id)::int assigned_employees FROM hr_shifts s LEFT JOIN hr_shift_assignments a ON a.shift_id=s.id WHERE s.company_id=$1 GROUP BY s.id ORDER BY s.name`,[u.companyId])).rows}
 async createShift(u:any,b:any){this.need(u,'hr.shifts.manage');const r=await this.db.query(`INSERT INTO hr_shifts(company_id,name,start_time,end_time,break_minutes,weekly_off) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[u.companyId,b.name,b.start_time,b.end_time,+b.break_minutes||0,JSON.stringify(b.weekly_off||[])]);await this.log(u,'shift.created','shift',r.rows[0].id);return r.rows[0]}
 async assignShift(u:any,id:string,b:any){this.need(u,'hr.shifts.manage');const r=await this.db.query(`INSERT INTO hr_shift_assignments(company_id,shift_id,employee_id,start_date,end_date) VALUES($1,$2,$3,$4,$5) RETURNING *`,[u.companyId,id,b.employee_id,b.start_date,b.end_date||null]);await this.log(u,'shift.assigned','shift',id,b.employee_id);return r.rows[0]}
 async leaves(u:any,q:any){this.need(u,'hr.leaves.view');return(await this.db.query(`SELECT l.*,${this.name} employee_name FROM hr_leave_requests l JOIN employees e ON e.id=l.employee_id WHERE l.company_id=$1 AND ($2::uuid IS NULL OR l.branch_id=$2) AND ($3='' OR l.status=$3) ORDER BY l.created_at DESC`,[u.companyId,this.br(u,q.branchId),q.status||''])).rows}
 async createLeave(u:any,b:any){this.need(u,'hr.leaves.apply','hr.leaves.manage');const days=Math.max(1,Math.floor((+new Date(b.end_date)-+new Date(b.start_date))/86400000)+1),r=await this.db.query(`INSERT INTO hr_leave_requests(company_id,branch_id,employee_id,leave_type,start_date,end_date,total_days,reason,attachment_url) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[u.companyId,b.branch_id||u.branchId||null,b.employee_id,b.leave_type,b.start_date,b.end_date,days,b.reason||null,b.attachment_url||null]);await this.log(u,'leave.submitted','leave',r.rows[0].id,b.employee_id);return r.rows[0]}
 async reviewLeave(u:any,id:string,b:any){this.need(u,'hr.leaves.approve');const r=await this.db.query(`UPDATE hr_leave_requests SET status=$1,review_comment=$2,reviewed_by=$3,reviewed_at=NOW(),updated_at=NOW() WHERE id=$4 AND company_id=$5 RETURNING *`,[b.status,b.comment||null,u.sub||null,id,u.companyId]);if(!r.rows[0])throw new NotFoundException();await this.log(u,'leave.'+b.status,'leave',id,r.rows[0].employee_id);return r.rows[0]}
 async payroll(u:any,q:any){this.need(u,'payroll.view','hr.payroll.view');return(await this.db.query(`SELECT p.*,${this.name} employee_name FROM hr_payroll_records p JOIN employees e ON e.id=p.employee_id WHERE p.company_id=$1 AND ($2::uuid IS NULL OR p.branch_id=$2) AND ($3::int IS NULL OR p.period_month=$3) AND ($4::int IS NULL OR p.period_year=$4) ORDER BY employee_name`,[u.companyId,this.br(u,q.branchId),q.month?+q.month:null,q.year?+q.year:null])).rows}
 async generatePayroll(u:any,b:any){this.need(u,'payroll.manage','hr.payroll.manage');const list=await this.employees(u,{branchId:b.branch_id}),out=[];for(const e of list.filter((x:any)=>x.status==='active')){const basic=+e.basic_salary||0,allow=(+e.housing_allowance||0)+(+e.transport_allowance||0)+(+e.other_allowance||0),net=basic+allow+(+b.overtime||0)+(+b.commission||0)+(+b.bonus||0)-(+b.deductions||0),r=await this.db.query(`INSERT INTO hr_payroll_records(company_id,branch_id,employee_id,period_month,period_year,basic_salary,allowances,overtime,commission,bonus,deductions,net_salary) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT(company_id,employee_id,period_month,period_year) DO UPDATE SET basic_salary=EXCLUDED.basic_salary,allowances=EXCLUDED.allowances,overtime=EXCLUDED.overtime,commission=EXCLUDED.commission,bonus=EXCLUDED.bonus,deductions=EXCLUDED.deductions,net_salary=EXCLUDED.net_salary,updated_at=NOW() RETURNING *`,[u.companyId,e.branch_id||null,e.id,+b.month,+b.year,basic,allow,+b.overtime||0,+b.commission||0,+b.bonus||0,+b.deductions||0,net]);out.push(r.rows[0])}await this.log(u,'payroll.generated','payroll',undefined,undefined,{month:b.month,year:b.year,count:out.length});return{generated:out.length,records:out}}
 async markPaid(u:any,id:string,b:any){this.need(u,'payroll.manage','hr.payroll.manage');const r=await this.db.query(`UPDATE hr_payroll_records SET status='paid',paid_at=NOW(),payment_reference=$1 WHERE id=$2 AND company_id=$3 RETURNING *`,[b.payment_reference||null,id,u.companyId]);if(!r.rows[0])throw new NotFoundException();await this.log(u,'payroll.paid','payroll',id,r.rows[0].employee_id);return r.rows[0]}
 async requests(u:any,q:any){this.need(u,'hr.requests.view');return(await this.db.query(`SELECT r.*,${this.name} employee_name FROM hr_requests r LEFT JOIN employees e ON e.id=r.employee_id WHERE r.company_id=$1 AND ($2::uuid IS NULL OR r.branch_id=$2) AND ($3='' OR r.status=$3) ORDER BY r.created_at DESC`,[u.companyId,this.br(u,q.branchId),q.status||''])).rows}
 async createRequest(u:any,b:any){this.need(u,'hr.requests.submit','hr.requests.manage');const r=await this.db.query(`INSERT INTO hr_requests(company_id,branch_id,employee_id,type,subject,details,attachment_url,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[u.companyId,b.branch_id||u.branchId||null,b.employee_id||null,b.type,b.subject||null,b.details||null,b.attachment_url||null,JSON.stringify(b.data||{})]);await this.log(u,'request.submitted','request',r.rows[0].id,b.employee_id);return r.rows[0]}
 async requestStatus(u:any,id:string,b:any){this.need(u,'hr.requests.manage');const r=await this.db.query(`UPDATE hr_requests SET status=$1,comment=$2,reviewed_by=$3,reviewed_at=NOW() WHERE id=$4 AND company_id=$5 RETURNING *`,[b.status,b.comment||null,u.sub||null,id,u.companyId]);if(!r.rows[0])throw new NotFoundException();await this.log(u,'request.'+b.status,'request',id,r.rows[0].employee_id);return r.rows[0]}
 async documents(u:any,q:any){this.need(u,'hr.documents.view');return(await this.db.query(`SELECT d.*,CASE WHEN expiry_date<CURRENT_DATE THEN 'expired' WHEN expiry_date<=CURRENT_DATE+7 THEN 'expires_7' WHEN expiry_date<=CURRENT_DATE+30 THEN 'expires_30' WHEN expiry_date<=CURRENT_DATE+60 THEN 'expires_60' WHEN expiry_date<=CURRENT_DATE+90 THEN 'expires_90' ELSE 'valid' END expiry_status,${this.name} employee_name FROM hr_documents d JOIN employees e ON e.id=d.employee_id WHERE d.company_id=$1 AND ($2::uuid IS NULL OR d.branch_id=$2) AND ($3::uuid IS NULL OR d.employee_id=$3) AND ($4='' OR d.document_type=$4) ORDER BY d.expiry_date NULLS LAST`,[u.companyId,this.br(u,q.branchId),q.employeeId||null,q.type||''])).rows}
 async createDocument(u:any,b:any){this.need(u,'hr.documents.manage');const r=await this.db.query(`INSERT INTO hr_documents(company_id,branch_id,employee_id,document_type,document_number,issue_date,expiry_date,attachment_url,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[u.companyId,b.branch_id||u.branchId||null,b.employee_id,b.document_type,b.document_number||null,b.issue_date||null,b.expiry_date||null,b.attachment_url||null,b.status||'valid']);await this.log(u,'document.created','document',r.rows[0].id,b.employee_id);return r.rows[0]}
 async updateDocument(u:any,id:string,b:any){this.need(u,'hr.documents.manage');const r=await this.db.query(`UPDATE hr_documents SET document_number=COALESCE($1,document_number),issue_date=COALESCE($2,issue_date),expiry_date=COALESCE($3,expiry_date),attachment_url=COALESCE($4,attachment_url),status=COALESCE($5,status),updated_at=NOW() WHERE id=$6 AND company_id=$7 RETURNING *`,[b.document_number||null,b.issue_date||null,b.expiry_date||null,b.attachment_url||null,b.status||null,id,u.companyId]);if(!r.rows[0])throw new NotFoundException();await this.log(u,'document.updated','document',id,r.rows[0].employee_id);return r.rows[0]}
 async report(u:any,t:string,q:any){this.need(u,'hr.reports.view');const m:any={employees:()=>this.employees(u,q),attendance:()=>this.attendance(u,q),leaves:()=>this.leaves(u,q),payroll:()=>this.payroll(u,q),iqama:()=>this.documents(u,{...q,type:'iqama'}),passport:()=>this.documents(u,{...q,type:'passport'}),contracts:()=>this.documents(u,{...q,type:'employment_contract'})};if(!m[t])throw new BadRequestException('Unknown report');return{type:t,generatedAt:new Date(),rows:await m[t]()}}
 async activity(u:any,l=50){this.need(u,'hr.audit.view','hr.reports.view');return(await this.db.query(`SELECT * FROM hr_activity_logs WHERE company_id=$1 ORDER BY created_at DESC LIMIT $2`,[u.companyId,Math.min(Math.max(l,1),200)])).rows}
}
