import { Injectable, NotFoundException } from '@nestjs/common';
import { DatabaseService } from '../database/database.service';
import { CreateLeaveTypeDto, UpdateLeaveTypeDto, CreateLeaveRequestDto, UpdateLeaveRequestDto, ApproveLeaveDto } from './leave.dto';
@Injectable()
export class LeaveService {
  constructor(private db: DatabaseService) {}
  async findAllTypes() { return (await this.db.query('SELECT * FROM leave_types ORDER BY name')).rows; }
  async findOneType(id: string) { const r=await this.db.query('SELECT * FROM leave_types WHERE id=$1',[id]); if(!r.rows[0]) throw new NotFoundException('Not found'); return r.rows[0]; }
  async createType(dto: CreateLeaveTypeDto) { return (await this.db.query('INSERT INTO leave_types(name,days_allowed,is_paid,description) VALUES($1,$2,$3,$4) RETURNING *',[dto.name,dto.daysAllowed,dto.isPaid??true,dto.description??null])).rows[0]; }
  async updateType(id: string, dto: UpdateLeaveTypeDto) { await this.findOneType(id); return (await this.db.query('UPDATE leave_types SET name=COALESCE($1,name),days_allowed=COALESCE($2,days_allowed),is_paid=COALESCE($3,is_paid),updated_at=NOW() WHERE id=$4 RETURNING *',[dto.name??null,dto.daysAllowed??null,dto.isPaid??null,id])).rows[0]; }
  async removeType(id: string) { await this.findOneType(id); await this.db.query('DELETE FROM leave_types WHERE id=$1',[id]); return {message:'Deleted'}; }
  async findAllRequests(employeeId?: string, status?: string) { let q='SELECT r.*,e.first_name,e.last_name,lt.name as leave_type_name FROM leave_requests r JOIN employees e ON e.id=r.employee_id LEFT JOIN leave_types lt ON lt.id=r.leave_type_id'; const p: any[]=[]; if(employeeId){q+=' WHERE r.employee_id=$1';p.push(employeeId);} if(status){q+=employeeId?' AND':' WHERE';q+=' r.status=$'+(p.length+1);p.push(status);} q+=' ORDER BY r.created_at DESC'; return (await this.db.query(q,p)).rows; }
  async findOneRequest(id: string) { const r=await this.db.query('SELECT r.*,e.first_name,e.last_name FROM leave_requests r JOIN employees e ON e.id=r.employee_id WHERE r.id=$1',[id]); if(!r.rows[0]) throw new NotFoundException('Not found'); return r.rows[0]; }
  async createRequest(dto: CreateLeaveRequestDto) { const days=Math.ceil((new Date(dto.endDate).getTime()-new Date(dto.startDate).getTime())/86400000)+1; return (await this.db.query('INSERT INTO leave_requests(employee_id,leave_type_id,start_date,end_date,total_days,reason) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[dto.employeeId,dto.leaveTypeId??null,dto.startDate,dto.endDate,days,dto.reason??null])).rows[0]; }
  async updateRequest(id: string, dto: UpdateLeaveRequestDto) { await this.findOneRequest(id); const days=dto.startDate&&dto.endDate?Math.ceil((new Date(dto.endDate).getTime()-new Date(dto.startDate).getTime())/86400000)+1:null; return (await this.db.query('UPDATE leave_requests SET start_date=COALESCE($1,start_date),end_date=COALESCE($2,end_date),total_days=COALESCE($3,total_days),reason=COALESCE($4,reason),updated_at=NOW() WHERE id=$5 RETURNING *',[dto.startDate??null,dto.endDate??null,days,dto.reason??null,id])).rows[0]; }
  async approveRequest(id: string, dto: ApproveLeaveDto) { await this.findOneRequest(id); return (await this.db.query('UPDATE leave_requests SET status=$1,approved_by=$2,approved_at=$3,rejection_reason=$4,updated_at=NOW() WHERE id=$5 RETURNING *',[dto.status,dto.approvedBy??null,dto.status==='approved'?new Date():null,dto.rejectionReason??null,id])).rows[0]; }
  async removeRequest(id: string) { await this.findOneRequest(id); await this.db.query('DELETE FROM leave_requests WHERE id=$1',[id]); return {message:'Deleted'}; }
  async getLeaveBalance(employeeId: string, year: number) { const types=(await this.findAllTypes()); const approved=(await this.db.query("SELECT * FROM leave_requests WHERE employee_id=$1 AND status='approved' AND EXTRACT(YEAR FROM start_date)=$2",[employeeId,year])).rows; return types.map((t:any)=>{const used=approved.filter((r:any)=>r.leave_type_id===t.id).reduce((s:number,r:any)=>s+r.total_days,0);return{leaveType:t,used,remaining:Math.max(0,t.days_allowed-used)};}); }
}
