import { Injectable, NotFoundException } from '@nestjs/common';
import { DatabaseService } from '../database/database.service';
import { CreatePayrollDto, UpdatePayrollDto, UpdatePayrollStatusDto, GeneratePayrollDto } from './payroll.dto';
@Injectable()
export class PayrollService {
  constructor(private db: DatabaseService) {}
  calc(basic: number, allowances: any[], deductions: any[]) { const ta=allowances.reduce((s:number,a:any)=>s+Number(a.amount||0),0); const td=deductions.reduce((s:number,d:any)=>s+Number(d.amount||0),0); const gross=Number(basic)+ta; return {totalAllowances:ta,totalDeductions:td,grossSalary:gross,netSalary:gross-td}; }
  async findAll(month?: number, year?: number, employeeId?: string) { let q='SELECT p.*,e.first_name,e.last_name,e.employee_id as emp_code FROM payroll p JOIN employees e ON e.id=p.employee_id WHERE 1=1'; const params: any[]=[]; if(month){q+=' AND p.month=$'+(params.length+1);params.push(month);} if(year){q+=' AND p.year=$'+(params.length+1);params.push(year);} if(employeeId){q+=' AND p.employee_id=$'+(params.length+1);params.push(employeeId);} q+=' ORDER BY p.year DESC,p.month DESC'; return (await this.db.query(q,params)).rows; }
  async findOne(id: string) { const r=await this.db.query('SELECT p.*,e.first_name,e.last_name FROM payroll p JOIN employees e ON e.id=p.employee_id WHERE p.id=$1',[id]); if(!r.rows[0]) throw new NotFoundException('Not found'); return r.rows[0]; }
  async create(dto: CreatePayrollDto) { const al=dto.allowances??[]; const de=dto.deductions??[]; const t=this.calc(dto.basicSalary,al,de); return (await this.db.query('INSERT INTO payroll(employee_id,month,year,basic_salary,allowances,deductions,total_allowances,total_deductions,gross_salary,net_salary,notes,present_days,absent_days,leave_days) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *',[dto.employeeId,dto.month,dto.year,dto.basicSalary,JSON.stringify(al),JSON.stringify(de),t.totalAllowances,t.totalDeductions,t.grossSalary,t.netSalary,dto.notes??null,dto.presentDays??0,dto.absentDays??0,dto.leaveDays??0])).rows[0]; }
  async update(id: string, dto: UpdatePayrollDto) { const ex=await this.findOne(id); const al=dto.allowances??ex.allowances; const de=dto.deductions??ex.deductions; const t=this.calc(dto.basicSalary??ex.basic_salary,al,de); return (await this.db.query('UPDATE payroll SET basic_salary=COALESCE($1,basic_salary),allowances=$2,deductions=$3,total_allowances=$4,total_deductions=$5,gross_salary=$6,net_salary=$7,notes=COALESCE($8,notes),present_days=COALESCE($9,present_days),absent_days=COALESCE($10,absent_days),leave_days=COALESCE($11,leave_days),updated_at=NOW() WHERE id=$12 RETURNING *',[dto.basicSalary??null,JSON.stringify(al),JSON.stringify(de),t.totalAllowances,t.totalDeductions,t.grossSalary,t.netSalary,dto.notes??null,dto.presentDays??null,dto.absentDays??null,dto.leaveDays??null,id])).rows[0]; }
  async updateStatus(id: string, dto: UpdatePayrollStatusDto) { await this.findOne(id); return (await this.db.query('UPDATE payroll SET status=$1,payment_date=$2,payment_method=$3,updated_at=NOW() WHERE id=$4 RETURNING *',[dto.status,dto.paymentDate??null,dto.paymentMethod??null,id])).rows[0]; }
  async remove(id: string) { await this.findOne(id); await this.db.query('DELETE FROM payroll WHERE id=$1',[id]); return {message:'Deleted'}; }
  async generate(dto: GeneratePayrollDto) { const {month,year}=dto; const from=`${year}-${String(month).padStart(2,'0')}-01`; const to=`${year}-${String(month).padStart(2,'0')}-${new Date(year,month,0).getDate()}`; const emps=dto.employeeIds?.length?(await this.db.query('SELECT * FROM employees WHERE id=ANY($1)',[dto.employeeIds])).rows:(await this.db.query("SELECT * FROM employees WHERE status='active'")).rows; const created=[]; for(const emp of emps){const ex=await this.db.query('SELECT id FROM payroll WHERE employee_id=$1 AND month=$2 AND year=$3',[emp.id,month,year]); if(ex.rows[0]) continue; const att=(await this.db.query('SELECT * FROM attendance WHERE employee_id=$1 AND date BETWEEN $2 AND $3',[emp.id,from,to])).rows; const present=att.filter((a:any)=>a.status==='present'||a.status==='late').length; const absent=att.filter((a:any)=>a.status==='absent').length; const leave=att.filter((a:any)=>a.status==='on_leave').length; const de=absent>0?[{label:'Absence Deduction',amount:Math.round((Number(emp.basic_salary)/30)*absent*100)/100}]:[]; const t=this.calc(emp.basic_salary,[],de); created.push((await this.db.query('INSERT INTO payroll(employee_id,month,year,basic_salary,allowances,deductions,total_allowances,total_deductions,gross_salary,net_salary,present_days,absent_days,leave_days) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *',[emp.id,month,year,emp.basic_salary,'[]',JSON.stringify(de),t.totalAllowances,t.totalDeductions,t.grossSalary,t.netSalary,present,absent,leave])).rows[0]);} return {generated:created.length,payrolls:created}; }
  async getMonthlySummary(month: number, year: number) { const p=await this.findAll(month,year); return {month,year,count:p.length,totalGross:p.reduce((s:number,x:any)=>s+Number(x.gross_salary),0),totalDeductions:p.reduce((s:number,x:any)=>s+Number(x.total_deductions),0),totalNet:p.reduce((s:number,x:any)=>s+Number(x.net_salary),0),paid:p.filter((x:any)=>x.status==='paid').length,pending:p.filter((x:any)=>x.status!=='paid').length}; }
}
