import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import api from '../../lib/api';
import { useToast } from '../../components/Toast';
import { getErr } from '../../lib/err';
const money=(n:any)=>`SAR ${Number(n||0).toFixed(2)}`;

export default function B2BSales(){
  const {toast}=useToast(),qc=useQueryClient();const [search,setSearch]=useState(''),[status,setStatus]=useState(''),[show,setShow]=useState(false),[catalogSearch,setCatalogSearch]=useState('');
  const [form,setForm]=useState<any>({warehouse_id:'',business_name:'',contact_name:'',phone:'',email:'',vat_number:'',cr_number:'',customer_po:'',payment_terms:'cash',credit_days:0,due_date:'',billing_address:'',shipping_address:'',notes:'',lines:[]});
  const {data={orders:[],summary:{}}}=useQuery({queryKey:['b2b-orders',status,search],queryFn:()=>api.get('/b2b/orders',{params:{status:status||undefined,search:search||undefined}}).then(r=>r.data)});
  const {data:warehouses=[]}=useQuery({queryKey:['warehouses'],queryFn:()=>api.get('/inventory/warehouses').then(r=>Array.isArray(r.data)?r.data:r.data?.data||[])});
  const {data:catalog=[]}=useQuery({queryKey:['b2b-catalog',form.warehouse_id,catalogSearch],enabled:!!form.warehouse_id,queryFn:()=>api.get('/b2b/catalog',{params:{warehouse_id:form.warehouse_id,search:catalogSearch||undefined}}).then(r=>r.data)});
  const total=useMemo(()=>form.lines.reduce((s:number,l:any)=>s+Number(l.quantity)*Number(l.unit_price)*(1-Number(l.discount_percent||0)/100),0)*1.15,[form.lines]);
  const create=useMutation({mutationFn:()=>api.post('/b2b/orders',form),onSuccess:r=>{toast(`Quotation ${r.data.order_number} created`,'success');setShow(false);setForm({...form,business_name:'',contact_name:'',phone:'',email:'',vat_number:'',cr_number:'',customer_po:'',lines:[]});qc.invalidateQueries({queryKey:['b2b-orders']})},onError:e=>toast(getErr(e),'error')});
  const action=useMutation({mutationFn:({id,next}:{id:string;next:string})=>api.patch(`/b2b/orders/${id}/status`,{status:next}),onSuccess:()=>{toast('Order updated','success');qc.invalidateQueries({queryKey:['b2b-orders']})},onError:e=>toast(getErr(e),'error')});
  const add=(p:any)=>setForm((f:any)=>({...f,lines:f.lines.some((x:any)=>x.variant_id===p.variant_id)?f.lines.map((x:any)=>x.variant_id===p.variant_id?{...x,quantity:x.quantity+1}:x):[...f.lines,{...p,quantity:1,unit_price:Number(p.wholesale_price||0),discount_percent:0}]}));
  const line=(id:string,k:string,v:any)=>setForm((f:any)=>({...f,lines:f.lines.map((x:any)=>x.variant_id===id?{...x,[k]:v}:x)}));
  return <div>
    <div className="nx-page-head"><div><h1 className="nx-page-title">B2B Warehouse Sales</h1><p className="nx-page-sub">Wholesale quotations, credit sales, delivery and receivables</p></div><button className="btn-nx primary" onClick={()=>setShow(true)}><i className="ti ti-plus"/> New B2B Quotation</button></div>
    <div className="nx-stats cols-4" style={{marginBottom:18}}>
      {[[data.summary.orders,'B2B Orders','ti-file-invoice','indigo'],[money(data.summary.sales),'Confirmed Sales','ti-chart-bar','green'],[money(data.summary.receivables),'Receivables','ti-wallet','amber'],[data.summary.overdue||0,'Overdue','ti-alert-triangle','red']].map((x:any)=><div className="nx-stat" key={x[1]}><div className={`nx-stat-icon ${x[3]}`}><i className={`ti ${x[2]}`}/></div><div className="nx-stat-body"><div className="nx-stat-val">{x[0]||0}</div><div className="nx-stat-lbl">{x[1]}</div></div></div>)}
    </div>
    <div className="nx-card" style={{padding:0,overflow:'hidden'}}><div style={{padding:14,display:'flex',gap:8,borderBottom:'1px solid var(--bd)'}}><input className="nx-input" placeholder="Search order, company or phone" value={search} onChange={e=>setSearch(e.target.value)} style={{width:280}}/><select className="nx-select" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="quotation">Quotation</option><option value="confirmed">Confirmed</option><option value="delivered">Delivered</option><option value="cancelled">Cancelled</option></select></div>
      <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Order','Business Customer','Warehouse','Qty','Total','Paid / Balance','Terms','Status','Actions'].map(h=><th key={h} style={{padding:11,textAlign:'left',fontSize:11,color:'var(--mu)',borderBottom:'1px solid var(--bd)'}}>{h}</th>)}</tr></thead><tbody>{data.orders.map((o:any)=><tr key={o.id} style={{borderBottom:'1px solid var(--bd)'}}><td style={{padding:11}}><b>{o.order_number}</b><small style={{display:'block',color:'var(--mu)'}}>{new Date(o.created_at).toLocaleDateString()}</small></td><td style={{padding:11}}><b>{o.business_name}</b><small style={{display:'block'}}>{o.phone||o.vat_number||'—'}</small></td><td style={{padding:11}}>{o.warehouse_name}</td><td style={{padding:11}}>{o.total_qty}</td><td style={{padding:11,fontWeight:700}}>{money(o.total)}</td><td style={{padding:11}}>{money(o.amount_paid)}<small style={{display:'block',color:Number(o.balance_due)>0?'#dc2626':'#059669'}}>Due {money(o.balance_due)}</small></td><td style={{padding:11}}>{o.payment_terms}{o.credit_days?` · ${o.credit_days}d`:''}</td><td style={{padding:11}}><span className={`nx-badge ${o.status==='delivered'?'green':o.status==='confirmed'?'teal':o.status==='cancelled'?'red':'amber'}`}>{o.status}</span></td><td style={{padding:11,display:'flex',gap:5}}>{o.status==='quotation'&&<button className="btn-nx primary sm" onClick={()=>action.mutate({id:o.id,next:'confirmed'})}>Confirm</button>}{o.status==='confirmed'&&<button className="btn-nx primary sm" onClick={()=>action.mutate({id:o.id,next:'delivered'})}>Deliver</button>}{['quotation','confirmed'].includes(o.status)&&<button className="btn-nx ghost sm" onClick={()=>action.mutate({id:o.id,next:'cancelled'})}>Cancel</button>}</td></tr>)}</tbody></table>{!data.orders.length&&<div style={{padding:40,textAlign:'center',color:'var(--mu)'}}>No B2B orders found</div>}</div>
    </div>
    {show&&<div style={{position:'fixed',inset:0,zIndex:2000,background:'rgba(0,0,0,.55)',display:'flex',justifyContent:'center',padding:20}} onClick={()=>setShow(false)}><div style={{background:'var(--cd)',borderRadius:16,width:'min(1100px,100%)',height:'calc(100vh - 40px)',display:'flex',flexDirection:'column',overflow:'hidden'}} onClick={e=>e.stopPropagation()}>
      <div style={{padding:'16px 20px',borderBottom:'1px solid var(--bd)',display:'flex',justifyContent:'space-between'}}><div><h2 style={{margin:0}}>New B2B Quotation</h2><small style={{color:'var(--mu)'}}>Prices exclude VAT · 15% VAT added automatically</small></div><button className="btn-nx ghost sm" onClick={()=>setShow(false)}>✕</button></div>
      <div style={{padding:18,overflowY:'auto',display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>
        <div style={{display:'grid',gap:10}}><h3 style={{margin:0}}>Business customer & terms</h3><select className="nx-select" value={form.warehouse_id} onChange={e=>setForm({...form,warehouse_id:e.target.value,lines:[]})}><option value="">Source warehouse *</option>{warehouses.map((w:any)=><option key={w.id} value={w.id}>{w.name}</option>)}</select><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}>{[['business_name','Business name *'],['contact_name','Contact person'],['phone','Phone'],['email','Email'],['vat_number','VAT number'],['cr_number','CR number'],['customer_po','Customer PO #']].map(([k,p])=><input key={k} className="nx-input" placeholder={p} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8}}><select className="nx-select" value={form.payment_terms} onChange={e=>setForm({...form,payment_terms:e.target.value})}><option value="cash">Cash / advance</option><option value="credit">Credit</option><option value="partial">Partial advance</option></select><input className="nx-input" type="number" placeholder="Credit days" value={form.credit_days} onChange={e=>setForm({...form,credit_days:e.target.value})}/><input className="nx-input" type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></div><textarea className="nx-input" placeholder="Shipping address" value={form.shipping_address} onChange={e=>setForm({...form,shipping_address:e.target.value})}/><textarea className="nx-input" placeholder="Notes / delivery instructions" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/>
          <h3 style={{margin:'8px 0 0'}}>Selected products</h3>{form.lines.map((l:any)=><div key={l.variant_id} style={{display:'grid',gridTemplateColumns:'1.5fr .55fr .75fr .55fr auto',gap:6,alignItems:'center',padding:8,border:'1px solid var(--bd)',borderRadius:8}}><div><b>{l.product_name}</b><small style={{display:'block'}}>{l.sku} · {[l.size,l.color].filter(Boolean).join(' / ')}</small></div><input className="nx-input" type="number" min="1" value={l.quantity} onChange={e=>line(l.variant_id,'quantity',Number(e.target.value))}/><input className="nx-input" type="number" value={l.unit_price} onChange={e=>line(l.variant_id,'unit_price',Number(e.target.value))}/><input className="nx-input" type="number" placeholder="Disc %" value={l.discount_percent} onChange={e=>line(l.variant_id,'discount_percent',Number(e.target.value))}/><button className="btn-nx ghost sm" onClick={()=>setForm({...form,lines:form.lines.filter((x:any)=>x.variant_id!==l.variant_id)})}>✕</button></div>)}<div style={{padding:14,background:'var(--bg)',borderRadius:10,display:'flex',justifyContent:'space-between'}}><b>Total incl. VAT</b><strong style={{fontSize:20,color:'var(--ac)'}}>{money(total)}</strong></div>
        </div>
        <div style={{display:'flex',flexDirection:'column',minHeight:0}}><h3 style={{margin:'0 0 10px'}}>Search warehouse stock</h3><input className="nx-input" placeholder="Search product, SKU, barcode, size or color" value={catalogSearch} onChange={e=>setCatalogSearch(e.target.value)} disabled={!form.warehouse_id}/><div style={{overflowY:'auto',marginTop:8,border:'1px solid var(--bd)',borderRadius:10}}>{catalog.map((p:any)=><div key={p.variant_id} style={{padding:10,borderBottom:'1px solid var(--bd)',display:'flex',alignItems:'center',gap:8}}><div style={{flex:1}}><b>{p.product_name}</b><small style={{display:'block',color:'var(--mu)'}}>{p.sku} · {[p.size,p.color].filter(Boolean).join(' / ')} · Available {p.available}</small></div><div style={{textAlign:'right'}}><b>{money(p.wholesale_price)}</b><small style={{display:'block'}}>Retail {money(p.retail_price)}</small></div><button className="btn-nx primary sm" disabled={p.available<=0} onClick={()=>add(p)}>Add</button></div>)}{form.warehouse_id&&!catalog.length&&<div style={{padding:30,textAlign:'center',color:'var(--mu)'}}>No matching stock</div>}</div></div>
      </div><div style={{padding:14,borderTop:'1px solid var(--bd)',display:'flex',justifyContent:'flex-end',gap:8}}><button className="btn-nx ghost" onClick={()=>setShow(false)}>Cancel</button><button className="btn-nx primary" disabled={!form.business_name||!form.warehouse_id||!form.lines.length||create.isPending} onClick={()=>create.mutate()}>{create.isPending?'Creating...':'Create Quotation'}</button></div>
    </div></div>}
  </div>
}
