import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import api from '../../lib/api';
import { useToast } from '../../components/Toast';
import { getErr } from '../../lib/err';

const money=(v:any)=>'SAR '+Number(v||0).toLocaleString('en-SA',{minimumFractionDigits:2,maximumFractionDigits:2});
const nav=(s:string)=>window.dispatchEvent(new CustomEvent('nav',{detail:s}));
const statusClass:Record<string,string>={paid:'active',confirmed:'pending',partial_return:'blue',refunded:'danger',cancelled:'inactive'};

export default function Ecommerce(){
  const [tab,setTab]=useState<'overview'|'orders'|'catalog'|'content'|'settings'>('overview');const [q,setQ]=useState('');
  const {data:config}=useQuery({queryKey:['store-config-admin'],queryFn:()=>api.get('/storefront/config').then(r=>r.data)});
  const {data:catalog,isLoading:catalogLoading}=useQuery({queryKey:['store-catalog-admin'],queryFn:()=>api.get('/storefront/catalog').then(r=>r.data)});
  const {data:allOrders=[],isLoading:ordersLoading,refetch,isFetching}=useQuery<any[]>({queryKey:['ecommerce-orders'],queryFn:()=>api.get('/sales/orders').then(r=>Array.isArray(r.data)?r.data:[])});
  const orders=useMemo(()=>allOrders.filter(o=>String(o.order_number||'').startsWith('WEB-')).filter(o=>!q||String(o.order_number).toLowerCase().includes(q.toLowerCase())||String(o.customer_name||'').toLowerCase().includes(q.toLowerCase())),[allOrders,q]);
  const products:any[]=catalog?.products||[];const variants=products.flatMap(p=>p.variants||[]);const liveProducts=products.filter(p=>(p.variants||[]).some((v:any)=>Number(v.stock)>0&&Number(v.selling_price)>0)).length;
  const revenue=orders.filter(o=>o.status==='paid').reduce((s,o)=>s+Number(o.total||0),0);const pending=orders.filter(o=>o.status==='confirmed').length;const units=orders.reduce((s,o)=>s+Number(o.item_count||0),0);
  return <div className="ecom-admin">
    <div className="nx-page-head"><div><h1 className="nx-page-title">E-commerce Store</h1><p className="nx-page-sub">Manage your NuxFashion website catalog, checkout and online orders.</p></div><div className="orders-head-actions"><button className="btn-nx ghost" onClick={()=>refetch()}><i className={`ti ti-refresh${isFetching?' login-spin':''}`}/> Refresh</button><a className="btn-nx ghost" href="/#store" target="_blank"><i className="ti ti-external-link"/> Open Store</a><button className="btn-nx primary" onClick={()=>nav('ad-orders')}><i className="ti ti-shopping-bag"/> Manage Orders</button></div></div>
    <div className="ecom-status"><div><i className="ti ti-world-check"/><span><b>Own Website</b><small>Public storefront available at /#store</small></span></div><span><i className="ti ti-circle-check-filled"/> Storefront Active</span></div>
    <div className="nx-stats cols-4"><Stat icon="ti-shopping-cart" tone="indigo" value={orders.length} label="Online Orders"/><Stat icon="ti-cash" tone="green" value={money(revenue)} label="Paid Revenue"/><Stat icon="ti-clock" tone="amber" value={pending} label="Awaiting Processing"/><Stat icon="ti-hanger-2" tone="teal" value={liveProducts} label="Live Products"/></div>
    <div className="nx-tabs">{([['overview','Overview'],['orders','Online Orders'],['catalog','Store Catalog'],['content','Banners & Content'],['settings','Store Settings']] as const).map(([id,title])=><button key={id} className={`nx-tab${tab===id?' on':''}`} onClick={()=>setTab(id)}>{title}</button>)}</div>
    {tab==='overview'&&<div className="ecom-overview">
      <section className="dash-panel"><header><div><h3>Store Performance</h3><p>Real data from website checkout</p></div></header><div className="dash-panel-body"><div className="ecom-metrics"><div><small>Average online order</small><b>{money(orders.length?orders.reduce((s,o)=>s+Number(o.total||0),0)/orders.length:0)}</b></div><div><small>Units ordered</small><b>{units}</b></div><div><small>Active variants</small><b>{variants.filter((v:any)=>Number(v.stock)>0).length}</b></div><div><small>Out-of-stock variants</small><b>{variants.filter((v:any)=>Number(v.stock)<=0).length}</b></div></div><div className="ecom-flow"><Flow icon="ti-world" title="Customer Store" text="Browse products"/><i className="ti ti-arrow-right"/><Flow icon="ti-shopping-cart" title="Checkout" text="VAT & delivery"/><i className="ti ti-arrow-right"/><Flow icon="ti-package-export" title="ERP Order" text="Stock deducted"/><i className="ti ti-arrow-right"/><Flow icon="ti-truck-delivery" title="Fulfilment" text="Admin processing"/></div></div></section>
      <section className="dash-panel"><header><div><h3>Store Readiness</h3><p>Required operating configuration</p></div></header><div className="dash-panel-body"><Ready ok={products.length>0} text="Online catalog published"/><Ready ok={variants.some((v:any)=>Number(v.stock)>0)} text="Sellable stock available"/><Ready ok text="VAT 15% checkout"/><Ready ok text="COD and bank transfer"/><Ready ok={false} text="Online card gateway"/><Ready ok={false} text="Courier API integration"/></div></section>
    </div>}
    {tab==='orders'&&<div><div className="nx-toolbar"><div className="nx-search"><i className="ti ti-search"/><input className="nx-input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Order or customer…"/></div><div className="nx-toolbar-right"><button className="btn-nx primary" onClick={()=>nav('ad-orders')}>Open Order Control Center <i className="ti ti-arrow-right"/></button></div></div><div className="nx-table-wrap"><table className="nx-table"><thead><tr><th>Online Order</th><th>Customer</th><th>Items</th><th>Payment</th><th>Total</th><th>Status</th><th>Date</th></tr></thead><tbody>{ordersLoading?<tr><td colSpan={7}><Empty text="Loading online orders…"/></td></tr>:!orders.length?<tr><td colSpan={7}><Empty text="No online orders yet"/></td></tr>:orders.map(o=><tr key={o.id}><td><b className="order-number">#{o.order_number}</b></td><td><b>{o.customer_name}</b><small className="table-sub">{o.customer_phone}</small></td><td>{o.item_count||0}</td><td><span className="payment-pill">{String(o.notes||'').includes('bank_transfer')?'Bank Transfer':'Cash on Delivery'}</span></td><td><b>{money(o.total)}</b></td><td><span className={`nx-badge ${statusClass[o.status]||'inactive'}`}>{o.status}</span></td><td>{new Date(o.created_at).toLocaleString('en-SA')}</td></tr>)}</tbody></table></div></div>}
    {tab==='catalog'&&<div><div className="ecom-catalog-head"><span>{products.length} products · {variants.length} variants</span><button className="btn-nx primary" onClick={()=>nav('ad-prod')}><i className="ti ti-edit"/> Manage Products</button></div><div className="nx-table-wrap"><table className="nx-table"><thead><tr><th>Product</th><th>Category</th><th>Variants</th><th>Starting Price</th><th>Available Stock</th><th>Website Status</th></tr></thead><tbody>{catalogLoading?<tr><td colSpan={6}><Empty text="Loading catalog…"/></td></tr>:products.map(p=>{const pv=p.variants||[];const sellable=pv.filter((v:any)=>Number(v.stock)>0&&Number(v.selling_price)>0);return <tr key={p.id}><td><b>{p.name}</b><small className="table-sub">{p.name_ar}</small></td><td>{p.category_name||'—'}</td><td>{pv.length}</td><td>{sellable.length?money(Math.min(...sellable.map((v:any)=>Number(v.selling_price)))):'—'}</td><td>{pv.reduce((s:number,v:any)=>s+Number(v.stock||0),0)}</td><td><span className={`nx-badge ${sellable.length?'active':'pending'}`}>{sellable.length?'Live':'Unavailable'}</span></td></tr>})}</tbody></table></div></div>}
    {tab==='content'&&<ContentManager/>}
    {tab==='settings'&&<div className="ecom-settings"><section><h3><i className="ti ti-truck-delivery"/> Delivery</h3><Row label="Standard delivery fee" value={money(config?.shipping_fee||25)}/><Row label="Free shipping threshold" value={money(config?.free_shipping_from||300)}/><Row label="Estimated delivery" value="2–5 business days"/></section><section><h3><i className="ti ti-receipt-tax"/> Tax & Currency</h3><Row label="Currency" value={config?.currency||'SAR'}/><Row label="VAT rate" value={`${config?.vat_rate||15}%`}/><Row label="Invoice integration" value="ERP + ZATCA QR"/></section><section><h3><i className="ti ti-credit-card"/> Payments</h3><Ready ok text="Cash on Delivery"/><Ready ok text="Bank Transfer"/><Ready ok={false} text="Mada / Apple Pay gateway"/><Ready ok={false} text="Tabby / Tamara gateway"/></section><div className="ecom-env-help"><i className="ti ti-settings-code"/> Delivery values can be changed on Railway API variables: <code>STOREFRONT_SHIPPING_FEE</code> and <code>STOREFRONT_FREE_SHIPPING_FROM</code>.</div></div>}
  </div>;
}
function Stat({icon,tone,value,label}:{icon:string;tone:string;value:any;label:string}){return <div className="nx-stat"><div className={`nx-stat-icon ${tone}`}><i className={`ti ${icon}`}/></div><div className="nx-stat-body"><div className="nx-stat-val">{value}</div><div className="nx-stat-lbl">{label}</div></div></div>}
function Flow({icon,title,text}:{icon:string;title:string;text:string}){return <div><i className={`ti ${icon}`}/><b>{title}</b><small>{text}</small></div>}
function Ready({ok=false,text}:{ok?:boolean;text:string}){return <div className={`ecom-ready ${ok?'ok':''}`}><i className={`ti ${ok?'ti-circle-check-filled':'ti-circle-dashed'}`}/><span>{text}</span><b>{ok?'Ready':'Next phase'}</b></div>}
function Row({label,value}:{label:string;value:string}){return <div className="setting-row"><span>{label}</span><b>{value}</b></div>}
function Empty({text}:{text:string}){return <div className="orders-empty"><i className="ti ti-shopping-bag-off"/><span>{text}</span></div>}

function ContentManager(){
  const qc=useQueryClient();const {toast}=useToast();const [editing,setEditing]=useState<any>(null);
  const {data,isLoading}=useQuery({queryKey:['store-admin-content'],queryFn:()=>api.get('/storefront/admin/content').then(r=>r.data)});
  const settings=data?.settings||{};const banners:any[]=data?.banners||[];
  const saveSettings=useMutation({mutationFn:(body:any)=>api.patch('/storefront/admin/settings',body),onSuccess:()=>{toast('Store content updated','success');qc.invalidateQueries({queryKey:['store-admin-content']});qc.invalidateQueries({queryKey:['store-config-admin']})},onError:(e:any)=>toast(getErr(e),'error')});
  const saveBanner=useMutation({mutationFn:(body:any)=>body.id?api.patch(`/storefront/admin/banners/${body.id}`,body):api.post('/storefront/admin/banners',body),onSuccess:()=>{toast('Banner saved','success');setEditing(null);qc.invalidateQueries({queryKey:['store-admin-content']})},onError:(e:any)=>toast(getErr(e),'error')});
  const remove=useMutation({mutationFn:(id:string)=>api.delete(`/storefront/admin/banners/${id}`),onSuccess:()=>{toast('Banner deleted','success');qc.invalidateQueries({queryKey:['store-admin-content']})}});
  if(isLoading)return <Empty text="Loading store content…"/>;
  return <div className="content-manager">
    <section className="content-settings"><header><div><h3>Storefront Content</h3><p>Change offers, delivery, promotional section and contact links.</p></div><a className="btn-nx ghost sm" href="/#store" target="_blank"><i className="ti ti-eye"/> Preview Store</a></header><SettingsForm initial={settings} saving={saveSettings.isPending} onSave={body=>saveSettings.mutate(body)}/></section>
    <section className="banner-manager"><header><div><h3>Hero Banner Slider</h3><p>Add multiple campaign banners; drag order is controlled by sort number.</p></div><button className="btn-nx primary sm" onClick={()=>setEditing({title:'',title_ar:'',subtitle:'',image_url:'',button_label:'Shop Now',button_link:'#collection',sort_order:banners.length,is_active:true})}><i className="ti ti-plus"/> Add Banner</button></header>{!banners.length?<div className="banner-empty"><i className="ti ti-photo-plus"/><b>No custom banners yet</b><span>The store currently uses its professional default hero.</span><button onClick={()=>setEditing({title:'',button_label:'Shop Now',button_link:'#collection',sort_order:0,is_active:true})}>Create first banner</button></div>:<div className="banner-grid">{banners.map(b=><article key={b.id}><div className="banner-preview">{b.image_url?<img src={b.image_url}/>:<i className="ti ti-photo"/>}<span className={`nx-badge ${b.is_active?'active':'inactive'}`}>{b.is_active?'Live':'Hidden'}</span></div><div><small>ORDER {b.sort_order}</small><h4>{b.title}</h4><p>{b.subtitle||'No subtitle'}</p><div><button onClick={()=>setEditing(b)}><i className="ti ti-edit"/> Edit</button><button className="danger" onClick={()=>confirm('Delete this banner?')&&remove.mutate(b.id)}><i className="ti ti-trash"/> Delete</button></div></div></article>)}</div>}</section>
    {editing&&<BannerModal value={editing} saving={saveBanner.isPending} onClose={()=>setEditing(null)} onSave={body=>saveBanner.mutate(body)}/>}
  </div>;
}
function SettingsForm({initial,saving,onSave}:{initial:any;saving:boolean;onSave:(b:any)=>void}){
  const [f,setF]=useState(initial);const set=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v}));
  return <form className="content-form" onSubmit={e=>{e.preventDefault();onSave(f)}}><label className="wide">Announcement (English)<input value={f.announcement||''} onChange={e=>set('announcement',e.target.value)}/></label><label className="wide">Announcement (Arabic)<input dir="rtl" value={f.announcement_ar||''} onChange={e=>set('announcement_ar',e.target.value)}/></label><label>Delivery fee (SAR)<input type="number" value={f.shipping_fee||0} onChange={e=>set('shipping_fee',Number(e.target.value))}/></label><label>Free delivery from (SAR)<input type="number" value={f.free_shipping_from||0} onChange={e=>set('free_shipping_from',Number(e.target.value))}/></label><label>Delivery estimate<input value={f.delivery_estimate||''} onChange={e=>set('delivery_estimate',e.target.value)}/></label><label>Return period (days)<input type="number" value={f.returns_days||0} onChange={e=>set('returns_days',Number(e.target.value))}/></label><label>Collection heading<input value={f.featured_title||''} onChange={e=>set('featured_title',e.target.value)}/></label><label>Collection heading Arabic<input dir="rtl" value={f.featured_title_ar||''} onChange={e=>set('featured_title_ar',e.target.value)}/></label><label className="wide">Promotional section title<input value={f.promo_title||''} onChange={e=>set('promo_title',e.target.value)}/></label><label className="wide">Promotional subtitle<textarea value={f.promo_subtitle||''} onChange={e=>set('promo_subtitle',e.target.value)}/></label><label className="wide">Promotional image URL<input value={f.promo_image_url||''} onChange={e=>set('promo_image_url',e.target.value)} placeholder="https://…"/></label><label>Support phone<input value={f.support_phone||''} onChange={e=>set('support_phone',e.target.value)}/></label><label>WhatsApp URL<input value={f.whatsapp_url||''} onChange={e=>set('whatsapp_url',e.target.value)}/></label><div className="wide content-save"><button className="btn-nx primary" disabled={saving}><i className="ti ti-device-floppy"/> {saving?'Saving…':'Save Store Content'}</button></div></form>;
}
function BannerModal({value,saving,onClose,onSave}:{value:any;saving:boolean;onClose:()=>void;onSave:(b:any)=>void}){
  const [f,setF]=useState(value);const set=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v}));
  return <div className="store-modal" onClick={onClose}><form className="banner-form-modal" onClick={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(f)}}><header><div><small>HOMEPAGE SLIDER</small><h2>{f.id?'Edit Banner':'New Hero Banner'}</h2></div><button type="button" onClick={onClose}>×</button></header><div>{f.image_url&&<div className="banner-large-preview" style={{backgroundImage:`linear-gradient(90deg,rgba(15,41,37,.75),transparent),url("${f.image_url}")`}}><b>{f.title}</b><span>{f.subtitle}</span></div>}<label>Title *<input required value={f.title||''} onChange={e=>set('title',e.target.value)}/></label><label>Arabic title<input dir="rtl" value={f.title_ar||''} onChange={e=>set('title_ar',e.target.value)}/></label><label className="wide">Subtitle<textarea value={f.subtitle||''} onChange={e=>set('subtitle',e.target.value)}/></label><label className="wide">Banner image URL<input value={f.image_url||''} onChange={e=>set('image_url',e.target.value)} placeholder="Recommended 1920 × 800 image URL"/></label><label>Button label<input value={f.button_label||''} onChange={e=>set('button_label',e.target.value)}/></label><label>Button link<input value={f.button_link||''} onChange={e=>set('button_link',e.target.value)} placeholder="#collection"/></label><label>Slider order<input type="number" value={f.sort_order||0} onChange={e=>set('sort_order',Number(e.target.value))}/></label><label className="banner-active"><input type="checkbox" checked={f.is_active!==false} onChange={e=>set('is_active',e.target.checked)}/> Show banner on website</label></div><footer><button type="button" className="btn-nx ghost" onClick={onClose}>Cancel</button><button className="btn-nx primary" disabled={saving}>{saving?'Saving…':'Save Banner'}</button></footer></form></div>;
}
