import { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import api from '../../lib/api';
import { useToast } from '../../components/Toast';
import { getErr } from '../../lib/err';

const money=(v:any)=>'SAR '+Number(v||0).toLocaleString('en-SA',{minimumFractionDigits:2,maximumFractionDigits:2});
const nav=(s:string)=>window.dispatchEvent(new CustomEvent('nav',{detail:s}));
const statusClass:Record<string,string>={paid:'active',confirmed:'pending',partial_return:'blue',refunded:'danger',cancelled:'inactive'};

type EcommerceTab='overview'|'orders'|'catalog'|'content'|'settings';
type ContentWorkspace='home'|'hero'|'catalog'|'campaigns'|'footer'|'pages'|'general';
export default function Ecommerce({initialTab='overview',initialWorkspace='home'}:{initialTab?:EcommerceTab;initialWorkspace?:ContentWorkspace}){
  const [tab,setTab]=useState<EcommerceTab>(initialTab);const [q,setQ]=useState('');
  useEffect(()=>setTab(initialTab),[initialTab]);
  const pageMeta:Record<string,[string,string]>= {
    overview:['E-commerce Dashboard','Monitor online revenue, orders, catalog health and storefront readiness.'],
    orders:['Online Orders','Review website orders and continue fulfilment in the order control center.'],
    catalog:['Online Catalog','Control which products, variants, prices and stock are available online.'],
    settings:['Store Settings','Review checkout, delivery, tax, currency and payment configuration.'],
    'content-home':['Homepage Builder','Arrange, configure and publish storefront homepage sections.'],
    'content-hero':['Hero Banners','Manage bilingual desktop and mobile hero banners.'],
    'content-catalog':['Catalog Sections','Choose categories, products, brands and sliders shown on the storefront.'],
    'content-campaigns':['Campaign Content','Manage promotional and seasonal storefront campaigns.'],
    'content-pages':['Website Pages','Manage customer-service, company and legal website content.'],
    'content-footer':['Footer & Contact','Manage footer navigation, contact details and social links.'],
    'content-general':['General & SEO','Manage store identity, search metadata and website-wide configuration.'],
  };
  const [pageTitle,pageDescription]=pageMeta[tab==='content'?`content-${initialWorkspace}`:tab]||['E-commerce Store','Manage your online sales channel.'];
  const {data:config}=useQuery({queryKey:['store-config-admin'],queryFn:()=>api.get('/storefront/config').then(r=>r.data)});
  const {data:catalog,isLoading:catalogLoading}=useQuery({queryKey:['store-catalog-admin'],queryFn:()=>api.get('/storefront/catalog').then(r=>r.data)});
  const {data:allOrders=[],isLoading:ordersLoading,refetch,isFetching}=useQuery<any[]>({queryKey:['ecommerce-orders'],queryFn:()=>api.get('/sales/orders').then(r=>Array.isArray(r.data)?r.data:[])});
  const orders=useMemo(()=>allOrders.filter(o=>String(o.order_number||'').startsWith('WEB-')).filter(o=>!q||String(o.order_number).toLowerCase().includes(q.toLowerCase())||String(o.customer_name||'').toLowerCase().includes(q.toLowerCase())),[allOrders,q]);
  const products:any[]=catalog?.products||[];const variants=products.flatMap(p=>p.variants||[]);const liveProducts=products.filter(p=>(p.variants||[]).some((v:any)=>Number(v.stock)>0&&Number(v.selling_price)>0)).length;
  const revenue=orders.filter(o=>o.status==='paid').reduce((s,o)=>s+Number(o.total||0),0);const pending=orders.filter(o=>o.status==='confirmed').length;const units=orders.reduce((s,o)=>s+Number(o.item_count||0),0);
  return <div className="ecom-admin">
    <div className="nx-page-head"><div><h1 className="nx-page-title">{pageTitle}</h1><p className="nx-page-sub">{pageDescription}</p></div><div className="orders-head-actions"><button className="btn-nx ghost" onClick={()=>refetch()}><i className={`ti ti-refresh${isFetching?' login-spin':''}`}/> Refresh</button><a className="btn-nx ghost" href="https://nuxfashion-store.vercel.app" target="_blank"><i className="ti ti-external-link"/> Open Store</a>{tab==='overview'&&<button className="btn-nx primary" onClick={()=>nav('ad-ecom-orders')}><i className="ti ti-shopping-bag"/> Online Orders</button>}</div></div>
    <div className="ecom-status"><div><i className="ti ti-world-check"/><span><b>Own Website</b><small>Public storefront available at /#store</small></span></div><span><i className="ti ti-circle-check-filled"/> Storefront Active</span></div>
    <div className="nx-stats cols-4"><Stat icon="ti-shopping-cart" tone="indigo" value={orders.length} label="Online Orders"/><Stat icon="ti-cash" tone="green" value={money(revenue)} label="Paid Revenue"/><Stat icon="ti-clock" tone="amber" value={pending} label="Awaiting Processing"/><Stat icon="ti-hanger-2" tone="teal" value={liveProducts} label="Live Products"/></div>
    {tab==='overview'&&<div className="ecom-overview">
      <section className="ecom-command-center">
        <header><div><small>STORE CONTROL CENTER</small><h3>Manage your online business</h3><p>Use the E-commerce dropdown for full navigation or jump directly to a frequent task.</p></div><span><i className="ti ti-circle-check-filled"/> Live &amp; connected</span></header>
        <div>{[
          ['ad-ecom-home','ti-layout-dashboard','Homepage Builder','Arrange storefront sections'],
          ['ad-ecom-banners','ti-photo','Hero Banners','Desktop, mobile, English & Arabic'],
          ['ad-ecom-catalog','ti-category','Online Catalog','Products, prices and availability'],
          ['ad-ecom-orders','ti-shopping-bag','Online Orders','Process and fulfil orders'],
          ['ad-ecom-campaigns','ti-speakerphone','Campaign Content','Promotions and seasonal content'],
          ['ad-ecom-settings','ti-settings','Store Settings','Delivery, VAT and payments'],
        ].map(([id,icon,title,text])=><button key={id} onClick={()=>nav(id)}><i className={`ti ${icon}`}/><span><b>{title}</b><small>{text}</small></span><i className="ti ti-chevron-right"/></button>)}</div>
      </section>
      <section className="dash-panel"><header><div><h3>Store Performance</h3><p>Real data from website checkout</p></div></header><div className="dash-panel-body"><div className="ecom-metrics"><div><small>Average online order</small><b>{money(orders.length?orders.reduce((s,o)=>s+Number(o.total||0),0)/orders.length:0)}</b></div><div><small>Units ordered</small><b>{units}</b></div><div><small>Active variants</small><b>{variants.filter((v:any)=>Number(v.stock)>0).length}</b></div><div><small>Out-of-stock variants</small><b>{variants.filter((v:any)=>Number(v.stock)<=0).length}</b></div></div><div className="ecom-flow"><Flow icon="ti-world" title="Customer Store" text="Browse products"/><i className="ti ti-arrow-right"/><Flow icon="ti-shopping-cart" title="Checkout" text="VAT & delivery"/><i className="ti ti-arrow-right"/><Flow icon="ti-package-export" title="ERP Order" text="Stock deducted"/><i className="ti ti-arrow-right"/><Flow icon="ti-truck-delivery" title="Fulfilment" text="Admin processing"/></div></div></section>
      <section className="dash-panel"><header><div><h3>Store Readiness</h3><p>Required operating configuration</p></div></header><div className="dash-panel-body"><Ready ok={products.length>0} text="Online catalog published"/><Ready ok={variants.some((v:any)=>Number(v.stock)>0)} text="Sellable stock available"/><Ready ok text="VAT 15% checkout"/><Ready ok text="COD and bank transfer"/><Ready ok={false} text="Online card gateway"/><Ready ok={false} text="Courier API integration"/></div></section>
    </div>}
    {tab==='orders'&&<div><div className="nx-toolbar"><div className="nx-search"><i className="ti ti-search"/><input className="nx-input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Order or customer…"/></div><div className="nx-toolbar-right"><button className="btn-nx primary" onClick={()=>nav('ad-orders')}>Open Order Control Center <i className="ti ti-arrow-right"/></button></div></div><div className="nx-table-wrap"><table className="nx-table"><thead><tr><th>Online Order</th><th>Customer</th><th>Items</th><th>Payment</th><th>Total</th><th>Status</th><th>Date</th></tr></thead><tbody>{ordersLoading?<tr><td colSpan={7}><Empty text="Loading online orders…"/></td></tr>:!orders.length?<tr><td colSpan={7}><Empty text="No online orders yet"/></td></tr>:orders.map(o=><tr key={o.id}><td><b className="order-number">#{o.order_number}</b></td><td><b>{o.customer_name}</b><small className="table-sub">{o.customer_phone}</small></td><td>{o.item_count||0}</td><td><span className="payment-pill">{String(o.notes||'').includes('bank_transfer')?'Bank Transfer':'Cash on Delivery'}</span></td><td><b>{money(o.total)}</b></td><td><span className={`nx-badge ${statusClass[o.status]||'inactive'}`}>{o.status}</span></td><td>{new Date(o.created_at).toLocaleString('en-SA')}</td></tr>)}</tbody></table></div></div>}
    {tab==='catalog'&&<div><div className="ecom-catalog-head"><span>{products.length} products · {variants.length} variants</span><button className="btn-nx primary" onClick={()=>nav('ad-prod')}><i className="ti ti-edit"/> Manage Products</button></div><div className="nx-table-wrap"><table className="nx-table"><thead><tr><th>Product</th><th>Category</th><th>Variants</th><th>Starting Price</th><th>Available Stock</th><th>Website Status</th></tr></thead><tbody>{catalogLoading?<tr><td colSpan={6}><Empty text="Loading catalog…"/></td></tr>:products.map(p=>{const pv=p.variants||[];const sellable=pv.filter((v:any)=>Number(v.stock)>0&&Number(v.selling_price)>0);return <tr key={p.id}><td><b>{p.name}</b><small className="table-sub">{p.name_ar}</small></td><td>{p.category_name||'—'}</td><td>{pv.length}</td><td>{sellable.length?money(Math.min(...sellable.map((v:any)=>Number(v.selling_price)))):'—'}</td><td>{pv.reduce((s:number,v:any)=>s+Number(v.stock||0),0)}</td><td><span className={`nx-badge ${sellable.length?'active':'pending'}`}>{sellable.length?'Live':'Unavailable'}</span></td></tr>})}</tbody></table></div></div>}
    {tab==='content'&&<ContentManager initialWorkspace={initialWorkspace}/>} 
    {tab==='settings'&&<div className="ecom-settings"><section><h3><i className="ti ti-truck-delivery"/> Delivery</h3><Row label="Standard delivery fee" value={money(config?.shipping_fee||25)}/><Row label="Free shipping threshold" value={money(config?.free_shipping_from||300)}/><Row label="Estimated delivery" value="2–5 business days"/></section><section><h3><i className="ti ti-receipt-tax"/> Tax & Currency</h3><Row label="Currency" value={config?.currency||'SAR'}/><Row label="VAT rate" value={`${config?.vat_rate||15}%`}/><Row label="Invoice integration" value="ERP + ZATCA QR"/></section><section><h3><i className="ti ti-credit-card"/> Payments</h3><Ready ok text="Cash on Delivery"/><Ready ok text="Bank Transfer"/><Ready ok={false} text="Mada / Apple Pay gateway"/><Ready ok={false} text="Tabby / Tamara gateway"/></section><div className="ecom-env-help"><i className="ti ti-settings-code"/> Delivery values can be changed on Railway API variables: <code>STOREFRONT_SHIPPING_FEE</code> and <code>STOREFRONT_FREE_SHIPPING_FROM</code>.</div></div>}
  </div>;
}
function Stat({icon,tone,value,label}:{icon:string;tone:string;value:any;label:string}){return <div className="nx-stat"><div className={`nx-stat-icon ${tone}`}><i className={`ti ${icon}`}/></div><div className="nx-stat-body"><div className="nx-stat-val">{value}</div><div className="nx-stat-lbl">{label}</div></div></div>}
function Flow({icon,title,text}:{icon:string;title:string;text:string}){return <div><i className={`ti ${icon}`}/><b>{title}</b><small>{text}</small></div>}
function Ready({ok=false,text}:{ok?:boolean;text:string}){return <div className={`ecom-ready ${ok?'ok':''}`}><i className={`ti ${ok?'ti-circle-check-filled':'ti-circle-dashed'}`}/><span>{text}</span><b>{ok?'Ready':'Next phase'}</b></div>}
function Row({label,value}:{label:string;value:string}){return <div className="setting-row"><span>{label}</span><b>{value}</b></div>}
function Empty({text}:{text:string}){return <div className="orders-empty"><i className="ti ti-shopping-bag-off"/><span>{text}</span></div>}

function ContentManager({initialWorkspace='home'}:{initialWorkspace?:ContentWorkspace}){
  const qc=useQueryClient();const {toast}=useToast();const [editing,setEditing]=useState<any>(null);const [workspace,setWorkspace]=useState<ContentWorkspace>(initialWorkspace);
  useEffect(()=>setWorkspace(initialWorkspace),[initialWorkspace]);
  const {data,isLoading}=useQuery({queryKey:['store-admin-content'],queryFn:()=>api.get('/storefront/admin/content').then(r=>r.data)});
  const settings=data?.settings||{};const banners:any[]=data?.banners||[];
  const saveSettings=useMutation({mutationFn:(body:any)=>api.patch('/storefront/admin/settings',body),onSuccess:()=>{toast('Store content updated','success');qc.invalidateQueries({queryKey:['store-admin-content']});qc.invalidateQueries({queryKey:['store-config-admin']})},onError:(e:any)=>toast(getErr(e),'error')});
  const refreshContent=()=>{qc.invalidateQueries({queryKey:['store-admin-content']});qc.invalidateQueries({queryKey:['store-config-admin']});qc.invalidateQueries({queryKey:['store-config']})};
  const saveBanner=useMutation({mutationFn:(body:any)=>body.id?api.patch(`/storefront/admin/banners/${body.id}`,body):api.post('/storefront/admin/banners',body),onSuccess:()=>{toast('Banner saved and published','success');setEditing(null);refreshContent()},onError:(e:any)=>toast(getErr(e),'error')});
  const remove=useMutation({mutationFn:(id:string)=>api.delete(`/storefront/admin/banners/${id}`),onSuccess:()=>{toast('Banner deleted','success');refreshContent()}});
  if(isLoading)return <Empty text="Loading store content…"/>;
  const workspaces=[['home','Homepage Layout','ti-layout-dashboard'],['hero','Hero Banners','ti-photo'],['catalog','Catalog Sections','ti-category'],['campaigns','Campaign Content','ti-speakerphone'],['footer','Footer & Contact','ti-layout-bottombar'],['pages','Website Pages','ti-file-text'],['general','General & SEO','ti-settings']];
  return <div className="content-manager single-workspace">
    <div className="ecom-workspace-body">
    {workspace==='home'&&<StoreBuilder initial={settings.homepage_sections||[]} saving={saveSettings.isPending} onSave={homepage_sections=>saveSettings.mutate({homepage_sections})}/>} 
    {workspace==='hero'&&<section className="banner-manager"><header><div><h3>Hero Banner Slider</h3><p>English, Arabic, desktop and mobile banners are managed here only.</p></div><button className="btn-nx primary sm" onClick={()=>setEditing({title:'',title_ar:'',subtitle:'',image_url:'',button_label:'Shop Now',button_link:'#collection',sort_order:banners.length,is_active:true})}><i className="ti ti-plus"/> Add Banner</button></header>{!banners.length?<div className="banner-empty"><i className="ti ti-photo-plus"/><b>No custom banners yet</b><span>The store currently uses its professional default hero.</span><button onClick={()=>setEditing({title:'',button_label:'Shop Now',button_link:'#collection',sort_order:0,is_active:true})}>Create first banner</button></div>:<div className="banner-grid">{banners.map(b=><article key={b.id}><div className="banner-preview">{b.image_url?<img src={b.image_url}/>:<i className="ti ti-photo"/>}<span className={`nx-badge ${b.is_active?'active':'inactive'}`}>{b.is_active?'Live':'Hidden'}</span></div><div><small>ORDER {b.sort_order}</small><h4>{b.title}</h4><p>{b.subtitle||'No subtitle'}</p><div><button onClick={()=>setEditing(b)}><i className="ti ti-edit"/> Edit</button><button className="danger" onClick={()=>confirm('Delete this banner?')&&remove.mutate(b.id)}><i className="ti ti-trash"/> Delete</button></div></div></article>)}</div>}</section>}
    {workspace!=='home'&&workspace!=='hero'&&<section className="content-settings"><header><div><h3>{workspaces.find(x=>x[0]===workspace)?.[1]}</h3><p>Only settings related to this area are shown.</p></div><a className="btn-nx ghost sm" href="https://nuxfashion-store.vercel.app" target="_blank"><i className="ti ti-eye"/> Preview Store</a></header><SettingsForm scope={workspace} initial={settings} saving={saveSettings.isPending} onSave={body=>saveSettings.mutate(body)}/>{workspace==='campaigns'&&<AssetGuide/>}</section>}
    </div>
    {editing&&<BannerModal value={editing} saving={saveBanner.isPending} onClose={()=>setEditing(null)} onSave={body=>saveBanner.mutate(body)}/>} 
  </div>;
}
const sectionTypes=[['hero','Hero banner'],['announcement','Announcement bar'],['categories','Category slider'],['flash','Flash deals'],['products','Product slider'],['promo_grid','Promotional banners'],['seasonal','Seasonal campaign'],['brands','Brand slider'],['trust','Why NuxStore?']];
function StoreBuilder({initial,saving,onSave}:{initial:any[];saving:boolean;onSave:(v:any[])=>void}){
  const defaults=initial.length?initial:[{id:'hero',type:'hero',title:'Hero Banner',enabled:true},{id:'categories',type:'categories',title:'Shop by Category',enabled:true},{id:'products',type:'products',title:'Featured Products',enabled:true}];
  const [rows,setRows]=useState<any[]>(defaults);const [drag,setDrag]=useState<number|null>(null);const [open,setOpen]=useState<string|null>(null);
  const {data:catalog={}}=useQuery({queryKey:['store-builder-catalog'],queryFn:()=>api.get('/storefront/catalog').then(r=>r.data)});
  const change=(id:string,body:any)=>setRows(x=>x.map(r=>r.id===id?{...r,...body}:r));
  const add=(type:string)=>{const id=`${type}-${Date.now()}`;const items=type==='promo_grid'?[{id:`banner-${Date.now()}`,title:'New campaign',title_ar:'حملة جديدة',subtitle:'Campaign subtitle',subtitle_ar:'وصف الحملة',image:'',link:'/category/all'}]:undefined;setRows(x=>[...x,{id,type,title:sectionTypes.find(s=>s[0]===type)?.[1]||'Section',title_ar:'',enabled:true,autoplay_seconds:3,layout:type==='promo_grid'?'two':'slider',items}]);setOpen(id)};
  const duplicate=(row:any)=>{const copy={...row,id:`${row.type}-${Date.now()}`,title:`${row.title||'Section'} copy`};setRows(x=>[...x,copy]);setOpen(copy.id)};
  const drop=(to:number)=>{if(drag===null||drag===to)return setDrag(null);setRows(x=>{const n=[...x],m=n.splice(drag,1)[0];n.splice(to,0,m);return n});setDrag(null)};
  return <section className="store-builder"><header><div><small>VISUAL HOMEPAGE BUILDER</small><h3>Build your storefront</h3><p>Drag sections into order. Every section can be duplicated, hidden or configured independently.</p></div><div><a className="btn-nx ghost" target="_blank" href="https://nuxfashion-store.vercel.app"><i className="ti ti-eye"/> Live preview</a><button className="btn-nx primary" disabled={saving} onClick={()=>onSave(rows)}><i className="ti ti-device-floppy"/> {saving?'Publishing…':'Publish layout'}</button></div></header>
    <div className="builder-add"><span>Add section</span>{sectionTypes.map(([type,label])=><button key={type} onClick={()=>add(type)}><i className="ti ti-plus"/> {label}</button>)}</div>
    <div className="builder-canvas">{rows.map((row,i)=><article key={row.id} draggable onDragStart={()=>setDrag(i)} onDragOver={e=>e.preventDefault()} onDrop={()=>drop(i)} className={`${row.enabled===false?'is-hidden':''}${open===row.id?' is-open':''}`}>
      <div className="builder-row"><i className="ti ti-grip-vertical builder-grip"/><span className={`builder-icon ${row.type}`}><i className={`ti ${row.type==='hero'?'ti-photo':row.type==='products'?'ti-hanger':row.type==='categories'?'ti-category':row.type==='flash'?'ti-bolt':row.type==='promo_grid'?'ti-layout-grid':row.type==='brands'?'ti-rosette':row.type==='trust'?'ti-shield-check':'ti-layout'}`}/></span><div><b>{row.title||sectionTypes.find(s=>s[0]===row.type)?.[1]}</b><small>{sectionTypes.find(s=>s[0]===row.type)?.[1]} · Position {i+1}</small></div><label className="builder-switch"><input type="checkbox" checked={row.enabled!==false} onChange={e=>change(row.id,{enabled:e.target.checked})}/><span/></label><button onClick={()=>setOpen(open===row.id?null:row.id)} title="Configure"><i className="ti ti-adjustments"/></button><button onClick={()=>duplicate(row)} title="Duplicate"><i className="ti ti-copy"/></button><button className="danger" onClick={()=>confirm('Delete this homepage section?')&&setRows(x=>x.filter(r=>r.id!==row.id))} title="Delete"><i className="ti ti-trash"/></button></div>
      {open===row.id&&<div className="builder-config">
        <label>English heading<input value={row.title||''} onChange={e=>change(row.id,{title:e.target.value})}/></label>
        <label>Arabic heading<input dir="rtl" value={row.title_ar||''} onChange={e=>change(row.id,{title_ar:e.target.value})}/></label>
        {['hero','products','categories','flash'].includes(row.type)&&<label>Autoplay speed<select value={row.autoplay_seconds??3} onChange={e=>change(row.id,{autoplay_seconds:Number(e.target.value)})}><option value={0}>Off</option><option value={1}>1 second</option><option value={2}>2 seconds</option><option value={3}>3 seconds</option><option value={5}>5 seconds</option><option value={7}>7 seconds</option></select></label>}
        {row.type==='flash'&&<label>Offer end date &amp; time<input type="datetime-local" value={row.end_at||''} onChange={e=>change(row.id,{end_at:e.target.value})}/></label>}
        {row.type==='promo_grid'&&<><label>Banner layout<select value={row.layout||'two'} onChange={e=>change(row.id,{layout:e.target.value})}><option value="two">2 equal banners</option><option value="three">3 equal banners</option><option value="mosaic">1 large + 2 stacked</option></select></label><PromoItemsEditor value={row.items||[]} onChange={items=>change(row.id,{items})}/></>}
        {row.type==='products'&&<><label>Product source<select value={row.source||'manual'} onChange={e=>change(row.id,{source:e.target.value})}><option value="manual">Manual selection</option><option value="collection">Shop the Collection</option><option value="best_sellers">Best sellers</option><option value="trending">Trending</option><option value="flash">Discounted products</option></select></label><Picker title="Products in this slider" help="Search and select products. Their selection order is preserved." items={catalog.products||[]} value={row.product_ids||[]} onChange={v=>change(row.id,{product_ids:v,source:'manual'})}/></>}
        {row.type==='categories'&&<Picker title="Categories in this slider" help="Only selected categories appear; empty uses the main category selection." items={catalog.categories||[]} value={row.category_ids||[]} onChange={v=>change(row.id,{category_ids:v})}/>} 
      </div>}
    </article>)}</div>
    <footer><span><i className="ti ti-info-circle"/> Changes stay as draft until you press Publish layout.</span><button className="btn-nx primary" disabled={saving} onClick={()=>onSave(rows)}>Publish {rows.filter(x=>x.enabled!==false).length} active sections</button></footer>
  </section>
}
function PromoItemsEditor({value,onChange}:{value:any[];onChange:(v:any[])=>void}){
  const rows=value.length?value:[];
  const update=(i:number,body:any)=>onChange(rows.map((x,n)=>n===i?{...x,...body}:x));
  const upload=(i:number,file?:File)=>{if(!file)return;if(file.size>700*1024)return alert('Banner image must be 700 KB or smaller');const reader=new FileReader();reader.onload=()=>update(i,{image:String(reader.result)});reader.readAsDataURL(file)};
  return <div className="builder-banners"><header><div><b>Banner cards</b><small>Add as many cards as required. English and Arabic content stay side by side.</small></div><button type="button" onClick={()=>onChange([...rows,{id:`banner-${Date.now()}`,title:'New banner',title_ar:'لافتة جديدة',subtitle:'',subtitle_ar:'',image:'',link:'/category/all'}])}><i className="ti ti-plus"/> Add banner</button></header>
    {rows.map((item,i)=><article key={item.id||i}><div className="builder-banner-number">{i+1}</div><div className="builder-lang"><b>English</b><input placeholder="Title" value={item.title||''} onChange={e=>update(i,{title:e.target.value})}/><input placeholder="Subtitle" value={item.subtitle||''} onChange={e=>update(i,{subtitle:e.target.value})}/></div><div className="builder-lang" dir="rtl"><b>العربية</b><input placeholder="العنوان" value={item.title_ar||''} onChange={e=>update(i,{title_ar:e.target.value})}/><input placeholder="الوصف" value={item.subtitle_ar||''} onChange={e=>update(i,{subtitle_ar:e.target.value})}/></div><label className="builder-upload">Image<input type="file" accept="image/*" onChange={e=>upload(i,e.target.files?.[0])}/>{item.image&&<img src={item.image}/>}<small>Desktop 1200×600 px · mobile safe crop · max 700 KB</small></label><label>Destination link<input value={item.link||''} onChange={e=>update(i,{link:e.target.value})}/></label><button type="button" className="danger" onClick={()=>onChange(rows.filter((_,n)=>n!==i))}><i className="ti ti-trash"/></button></article>)}
  </div>
}
function SettingsForm({scope,initial,saving,onSave}:{scope:string;initial:any;saving:boolean;onSave:(b:any)=>void}){
  const [f,setF]=useState(initial);const set=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v}));
  const {data:catalog={}}=useQuery({queryKey:['store-catalog-cms-pickers'],queryFn:()=>api.get('/storefront/catalog').then(r=>r.data)});
  const upload=(key:string,file?:File)=>{if(!file)return;if(file.size>700*1024)return alert('Image must be 700 KB or smaller');const reader=new FileReader();reader.onload=()=>set(key,String(reader.result));reader.readAsDataURL(file)};
  return <form className="content-form scoped-store-form" onSubmit={e=>{e.preventDefault();onSave(f)}}>
    {scope==='catalog'&&<><div className="wide scope-intro"><i className="ti ti-category"/><div><b>Catalog homepage sections</b><small>Select exactly which categories, products and brands customers will see.</small></div></div><Picker title="Shop by Category" help="Only selected categories appear. Empty selection shows all active categories." items={catalog.categories||[]} value={f.category_ids||[]} onChange={v=>set('category_ids',v)}/><Picker title="Flash Deals" help="Selected products and their order." items={catalog.products||[]} value={f.flash_product_ids||[]} onChange={v=>set('flash_product_ids',v)}/><Picker title="Shop the Collection" help="Products for the collection slider." items={catalog.products||[]} value={f.collection_product_ids||[]} onChange={v=>set('collection_product_ids',v)}/><Picker title="Best Sellers" help="Manual selection overrides automatic tags." items={catalog.products||[]} value={f.best_seller_product_ids||[]} onChange={v=>set('best_seller_product_ids',v)}/><Picker title="Trending Now" help="Products for the trending slider." items={catalog.products||[]} value={f.trending_product_ids||[]} onChange={v=>set('trending_product_ids',v)}/><Picker title="Featured Brands" help="Only selected brands appear." items={catalog.brands||[]} value={f.featured_brand_ids||[]} onChange={v=>set('featured_brand_ids',v)}/></>}
    {scope==='campaigns'&&<><div className="wide scope-intro"><i className="ti ti-speakerphone"/><div><b>Campaign content</b><small>Seasonal campaign and customer trust content.</small></div></div><h4 className="wide content-form-title">Seasonal Campaign</h4><label>English title<input value={f.seasonal_title||''} onChange={e=>set('seasonal_title',e.target.value)}/></label><label>Arabic title<input dir="rtl" value={f.seasonal_title_ar||''} onChange={e=>set('seasonal_title_ar',e.target.value)}/></label><label className="wide">English subtitle<textarea value={f.seasonal_subtitle||''} onChange={e=>set('seasonal_subtitle',e.target.value)}/></label><label className="wide">Arabic subtitle<textarea dir="rtl" value={f.seasonal_subtitle_ar||''} onChange={e=>set('seasonal_subtitle_ar',e.target.value)}/></label><label>Button label<input value={f.seasonal_button_label||''} onChange={e=>set('seasonal_button_label',e.target.value)}/></label><label>Destination link<input value={f.seasonal_button_link||''} onChange={e=>set('seasonal_button_link',e.target.value)}/></label><label className="wide">Campaign image<input value={f.seasonal_image||''} onChange={e=>set('seasonal_image',e.target.value)}/><input type="file" accept="image/*" onChange={e=>upload('seasonal_image',e.target.files?.[0])}/><small>Recommended 1920×700 px · maximum 700 KB</small></label><h4 className="wide content-form-title">Why NuxStore?</h4><label>English heading<input value={f.trust_title||''} onChange={e=>set('trust_title',e.target.value)}/></label><label>Arabic heading<input dir="rtl" value={f.trust_title_ar||''} onChange={e=>set('trust_title_ar',e.target.value)}/></label><TrustEditor value={f.trust_items||[]} onChange={v=>set('trust_items',v)}/></>}
    {scope==='footer'&&<><div className="wide scope-intro"><i className="ti ti-address-book"/><div><b>Footer, contact and social channels</b><small>All storefront contact information in one place.</small></div></div><label>Contact phone<input value={f.contact_phone||''} onChange={e=>set('contact_phone',e.target.value)}/></label><label>Contact email<input value={f.contact_email||''} onChange={e=>set('contact_email',e.target.value)}/></label><label>English address<input value={f.contact_address||''} onChange={e=>set('contact_address',e.target.value)}/></label><label>Arabic address<input dir="rtl" value={f.contact_address_ar||''} onChange={e=>set('contact_address_ar',e.target.value)}/></label><label>Working hours<input value={f.contact_hours||''} onChange={e=>set('contact_hours',e.target.value)}/></label><label>Google Maps URL<input value={f.contact_map_url||''} onChange={e=>set('contact_map_url',e.target.value)}/></label>{['whatsapp','instagram','facebook','twitter','tiktok','snapchat','youtube'].map(k=><label key={k}>{k[0].toUpperCase()+k.slice(1)} URL<input value={f[`${k}_url`]||''} onChange={e=>set(`${k}_url`,e.target.value)}/></label>)}<h4 className="wide content-form-title">Footer Navigation</h4><FooterEditor f={f} set={set}/></>}
    {scope==='pages'&&<><div className="wide scope-intro"><i className="ti ti-files"/><div><b>Customer, company and legal pages</b><small>Open one page at a time and maintain English and Arabic copy together.</small></div></div><PageEditor f={f} set={set}/></>}
    {scope==='general'&&<><div className="wide scope-intro"><i className="ti ti-adjustments"/><div><b>Store identity, operations and SEO</b><small>Essential configuration only.</small></div></div><label>Store tagline<input value={f.store_tagline||''} onChange={e=>set('store_tagline',e.target.value)}/></label><label>Theme color<input type="color" value={f.primary_color||'#0f766e'} onChange={e=>set('primary_color',e.target.value)}/></label><label className="wide">Logo<input value={f.logo_url||''} onChange={e=>set('logo_url',e.target.value)}/><input type="file" accept="image/*" onChange={e=>upload('logo_url',e.target.files?.[0])}/></label><label>Delivery fee (SAR)<input type="number" value={f.shipping_fee||0} onChange={e=>set('shipping_fee',Number(e.target.value))}/></label><label>Free delivery from (SAR)<input type="number" value={f.free_shipping_from||0} onChange={e=>set('free_shipping_from',Number(e.target.value))}/></label><label>Delivery estimate<input value={f.delivery_estimate||''} onChange={e=>set('delivery_estimate',e.target.value)}/></label><label>Return period (days)<input type="number" value={f.returns_days||0} onChange={e=>set('returns_days',Number(e.target.value))}/></label><label>Footer about<input value={f.footer_about||''} onChange={e=>set('footer_about',e.target.value)}/></label><label>Footer about Arabic<input dir="rtl" value={f.footer_about_ar||''} onChange={e=>set('footer_about_ar',e.target.value)}/></label><label>Copyright<input value={f.footer_copyright||''} onChange={e=>set('footer_copyright',e.target.value)}/></label><label>Copyright Arabic<input dir="rtl" value={f.footer_copyright_ar||''} onChange={e=>set('footer_copyright_ar',e.target.value)}/></label><label>SEO page title<input value={f.seo_title||''} onChange={e=>set('seo_title',e.target.value)}/></label><label>SEO description<input value={f.seo_description||''} onChange={e=>set('seo_description',e.target.value)}/></label></>}
    <div className="wide content-save sticky-save"><span>Save changes for this section only</span><button className="btn-nx primary" disabled={saving}><i className="ti ti-device-floppy"/> {saving?'Saving…':'Save & Publish'}</button></div>
  </form>
}
function Picker({title,help,items,value,onChange}:{title:string;help:string;items:any[];value:string[];onChange:(v:string[])=>void}){const [q,setQ]=useState('');const shown=items.filter(x=>`${x.name||''} ${x.name_ar||''}`.toLowerCase().includes(q.toLowerCase())).slice(0,80);const toggle=(id:string)=>onChange(value.includes(id)?value.filter(x=>x!==id):[...value,id]);return <div className="wide" style={{border:'1px solid var(--line)',borderRadius:12,padding:14}}><b>{title} <span className="nx-badge blue">{value.length} selected</span></b><small style={{display:'block',color:'var(--muted)',margin:'4px 0 10px'}}>{help}</small><input className="nx-input" style={{width:'100%',marginBottom:10}} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search…"/><div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:7,maxHeight:220,overflow:'auto'}}>{shown.map(x=><label key={x.id} className="content-check"><input type="checkbox" checked={value.includes(x.id)} onChange={()=>toggle(x.id)}/><span>{x.name}<small style={{display:'block'}}>{x.name_ar}</small></span></label>)}</div>{value.length>0&&<button type="button" className="btn-nx ghost sm" style={{marginTop:10}} onClick={()=>onChange([])}>Clear selection / Show automatic</button>}</div>}
function TrustEditor({value,onChange}:{value:any[];onChange:(v:any[])=>void}){const rows=value.length?value:[{icon:'🔒',title:'Secure Payment',title_ar:'دفع آمن',description:'Secure checkout',description_ar:'دفع آمن'}];const change=(i:number,k:string,v:string)=>onChange(rows.map((x,n)=>n===i?{...x,[k]:v}:x));return <div className="wide">{rows.map((x,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'60px 1fr 1fr',gap:8,marginBottom:8}}><input value={x.icon||''} onChange={e=>change(i,'icon',e.target.value)}/><input value={x.title||''} onChange={e=>change(i,'title',e.target.value)} placeholder="English title"/><input dir="rtl" value={x.title_ar||''} onChange={e=>change(i,'title_ar',e.target.value)} placeholder="العنوان"/><span/><input value={x.description||''} onChange={e=>change(i,'description',e.target.value)} placeholder="English description"/><input dir="rtl" value={x.description_ar||''} onChange={e=>change(i,'description_ar',e.target.value)} placeholder="الوصف"/></div>)}<button type="button" className="btn-nx ghost sm" onClick={()=>onChange([...rows,{icon:'✓',title:'',title_ar:'',description:'',description_ar:''}])}>+ Add benefit</button></div>}
const footerDefaults:any={footer_customer_links:[['Track Order','تتبع الطلب','/{locale}/track'],['Returns & Exchanges','الإرجاع والاستبدال','/{locale}/returns'],['FAQs','الأسئلة الشائعة','/{locale}/faq'],['Contact Us','اتصل بنا','/{locale}/contact'],['Track Shipment','تتبع الشحنة','/{locale}/shipment']],footer_company_links:[['About NuxStore','عن نوكس ستور','/{locale}/about'],['Careers','الوظائف','/{locale}/careers'],['Press & Media','الصحافة والإعلام','/{locale}/press'],['Our Blog','مدونتنا','/{locale}/blog'],['Our Stores','متاجرنا','/{locale}/stores']],footer_legal_links:[['Privacy Policy','سياسة الخصوصية','/{locale}/privacy'],['Terms & Conditions','الشروط والأحكام','/{locale}/terms'],['Shipping Policy','سياسة الشحن','/{locale}/shipping-policy'],['Cookie Policy','سياسة ملفات الارتباط','/{locale}/cookies'],['Accessibility','إمكانية الوصول','/{locale}/accessibility']]};
function FooterEditor({f,set}:{f:any;set:any}){return <div className="wide">{Object.entries(footerDefaults).map(([key,defs]:any)=><div key={key} style={{marginBottom:16}}><b>{key.includes('customer')?'Customer Service':key.includes('company')?'Company':'Legal'}</b>{((f[key]?.length?f[key]:defs.map((d:any)=>({label:d[0],label_ar:d[1],url:d[2],enabled:true}))) as any[]).map((x,i,all)=><div key={i} style={{display:'grid',gridTemplateColumns:'1fr 1fr 1.2fr 70px',gap:7,marginTop:7}}><input value={x.label||''} onChange={e=>set(key,all.map((r,n)=>n===i?{...r,label:e.target.value}:r))}/><input dir="rtl" value={x.label_ar||''} onChange={e=>set(key,all.map((r,n)=>n===i?{...r,label_ar:e.target.value}:r))}/><input value={x.url||''} onChange={e=>set(key,all.map((r,n)=>n===i?{...r,url:e.target.value}:r))}/><label className="content-check"><input type="checkbox" checked={x.enabled!==false} onChange={e=>set(key,all.map((r,n)=>n===i?{...r,enabled:e.target.checked}:r))}/>Show</label></div>)}</div>)}</div>}
const pages=[['about','About'],['careers','Careers'],['press','Press & Media'],['blog','Blog'],['stores','Our Stores'],['returns','Returns & Exchanges'],['faq','FAQs'],['privacy','Privacy Policy'],['terms','Terms & Conditions'],['shipping_policy','Shipping Policy'],['cookies','Cookie Policy'],['accessibility','Accessibility']];
function PageEditor({f,set}:{f:any;set:any}){return <div className="wide">{pages.map(([k,n])=><details key={k} style={{border:'1px solid var(--line)',borderRadius:10,padding:'10px 12px',marginBottom:8}}><summary style={{fontWeight:650,cursor:'pointer'}}>{n}</summary><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:10}}><textarea rows={6} value={f[`page_${k}`]||''} onChange={e=>set(`page_${k}`,e.target.value)} placeholder="English page content"/><textarea rows={6} dir="rtl" value={f[`page_${k}_ar`]||''} onChange={e=>set(`page_${k}_ar`,e.target.value)} placeholder="محتوى الصفحة بالعربية"/></div></details>)}</div>}
function AssetGuide(){return <div className="ecom-env-help"><b><i className="ti ti-ruler-2"/> Website Creative Guide</b><br/>Hero desktop: 1920×800 px · Hero mobile: 1080×1350 px · Promotional cards: 1200×600 px · Seasonal banner: 1920×700 px · Category image: 800×800 px · Product image: 1200×1500 px · Logo: 600×200 px transparent PNG/SVG. Use JPG/WebP for photos, keep each file below 700 KB, avoid placing important text at image edges, and provide both English and Arabic copy.</div>}
function BannerModal({value,saving,onClose,onSave}:{value:any;saving:boolean;onClose:()=>void;onSave:(b:any)=>void}){
  const [f,setF]=useState(value);const set=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v}));
  const upload=(key:string,file?:File)=>{if(!file)return;if(file.size>900*1024){alert('Please use a JPG/WebP image below 900 KB');return}const r=new FileReader();r.onload=()=>set(key,String(r.result));r.readAsDataURL(file)};
  const asset=(key:string,title:string,size:string,dir?:'rtl')=><label className="banner-upload-card" dir={dir}><b>{title}</b><small>{size} · JPG/WebP</small>{f[key]?<img src={f[key]} alt="Preview"/>:<span><i className="ti ti-cloud-upload"/> Drag or choose image</span>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(key,e.target.files?.[0])}/>{f[key]&&<button type="button" onClick={()=>set(key,'')}>Remove</button>}</label>;
  return <div className="store-modal" onClick={onClose}><form className="banner-form-modal easy-banner" onClick={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(f)}}>
    <header><div><small>HOMEPAGE HERO</small><h2>{f.id?'Edit Banner':'Add Banner'}</h2><p>English and Arabic assets stay side by side to prevent publishing mistakes.</p></div><button type="button" onClick={onClose}>×</button></header>
    <div className="banner-copy-grid"><section><h3>English content</h3><label>Title *<input required value={f.title||''} onChange={e=>set('title',e.target.value)}/></label><label>Subtitle<textarea value={f.subtitle||''} onChange={e=>set('subtitle',e.target.value)}/></label><label>Button label<input value={f.button_label||''} onChange={e=>set('button_label',e.target.value)}/></label></section><section dir="rtl"><h3>المحتوى العربي</h3><label>العنوان<input value={f.title_ar||''} onChange={e=>set('title_ar',e.target.value)}/></label><label>الوصف<textarea value={f.subtitle_ar||''} onChange={e=>set('subtitle_ar',e.target.value)}/></label><label>نص الزر<input value={f.button_label_ar||''} onChange={e=>set('button_label_ar',e.target.value)}/></label></section></div>
    <div className="banner-assets-grid">{asset('image_url','English · Desktop','1920 × 720 px')}{asset('image_url_ar','العربية · سطح المكتب','1920 × 720 px','rtl')}{asset('mobile_image_url','English · Mobile','1080 × 1350 px')}{asset('mobile_image_url_ar','العربية · الجوال','1080 × 1350 px','rtl')}</div>
    <div className="banner-options"><label>Destination link<input value={f.button_link||''} onChange={e=>set('button_link',e.target.value)} placeholder="/category/new"/></label><label>Display order<input type="number" value={f.sort_order||0} onChange={e=>set('sort_order',Number(e.target.value))}/></label><label>Start<input type="datetime-local" value={f.starts_at?String(f.starts_at).slice(0,16):''} onChange={e=>set('starts_at',e.target.value||null)}/></label><label>End<input type="datetime-local" value={f.ends_at?String(f.ends_at).slice(0,16):''} onChange={e=>set('ends_at',e.target.value||null)}/></label><label className="banner-active"><input type="checkbox" checked={f.is_active!==false} onChange={e=>set('is_active',e.target.checked)}/> Published</label></div>
    <footer><button type="button" className="btn-nx ghost" onClick={onClose}>Save draft & close</button><button className="btn-nx primary" disabled={saving}>{saving?'Publishing…':'Publish Banner'}</button></footer>
  </form></div>;
}
