import {api} from '../../lib/api';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {useMemo,useState} from 'react';
import {useToast} from '../../components/Toast';
const cash=(v:any)=>`SAR ${Number(v||0).toLocaleString('en-SA',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const tone:Record<string,string>={draft:'grey',approved:'blue',partially_received:'pending',received:'active',cancelled:'danger'};
const label=(v:string)=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());
function Field({title,children}:any){return <label className="purch-field"><span>{title}</span>{children}</label>}
function Modal({title,sub,close,children,footer,wide=false}:any){return <div className="branch-modal-shade" onClick={close}><div className={`purch-modal ${wide?'wide':''}`} onClick={e=>e.stopPropagation()}><header><div><h2>{title}</h2><p>{sub}</p></div><button onClick={close}><i className="ti ti-x"/></button></header><div className="purch-modal-body">{children}</div><footer>{footer}</footer></div></div>}

function SupplierModal({supplier,close}:any){
  const qc=useQueryClient(),{toast}=useToast();const [f,setF]=useState({name:supplier?.name||'',code:supplier?.code||'',contact_person:supplier?.contact_person||'',phone:supplier?.phone||'',email:supplier?.email||'',address:supplier?.address||'',city:supplier?.city||'',tax_number:supplier?.tax_number||'',payment_terms:Number(supplier?.payment_terms??30),notes:supplier?.notes||''});
  const save=useMutation({mutationFn:()=>supplier?api.patch(`/purchasing/suppliers/${supplier.id}`,f):api.post('/purchasing/suppliers',f),onSuccess:()=>{qc.invalidateQueries({queryKey:['suppliers']});toast('Supplier saved');close()},onError:(e:any)=>toast(e.response?.data?.message||'Could not save supplier','error')});
  return <Modal title={supplier?'Edit Supplier':'New Supplier'} sub="Vendor identity, VAT details and payment terms" close={close} footer={<><button className="btn-nx ghost" onClick={close}>Cancel</button><button className="btn-nx primary" disabled={!f.name||save.isPending} onClick={()=>save.mutate()}>{save.isPending?'Saving…':'Save Supplier'}</button></>}>
    <div className="purch-form-grid">{[['Company Name *','name'],['Supplier Code','code'],['Contact Person','contact_person'],['Phone','phone'],['Email','email'],['VAT Number','tax_number'],['City','city'],['Address','address']].map(([a,k])=><Field key={k} title={a}><input value={(f as any)[k]} onChange={e=>setF(x=>({...x,[k]:e.target.value}))}/></Field>)}<Field title="Payment Terms"><select value={f.payment_terms} onChange={e=>setF(x=>({...x,payment_terms:Number(e.target.value)}))}>{[0,7,14,30,45,60,90].map(x=><option value={x} key={x}>{x?`Net ${x} days`:'Cash on delivery'}</option>)}</select></Field><Field title="Notes"><input value={f.notes} onChange={e=>setF(x=>({...x,notes:e.target.value}))}/></Field></div>
  </Modal>;
}

function POModal({close}:any){
  const qc=useQueryClient(),{toast}=useToast();const [search,setSearch]=useState('');const [f,setF]=useState<any>({supplier_id:'',warehouse_id:'',expected_date:'',freight_amount:'0',customs_amount:'0',other_costs:'0',notes:''});const [lines,setLines]=useState<Record<string,any>>({});
  const {data:suppliers=[]}=useQuery<any[]>({queryKey:['suppliers'],queryFn:()=>api.get('/purchasing/suppliers').then(r=>r.data)});
  const {data:warehouses=[]}=useQuery<any[]>({queryKey:['warehouses'],queryFn:()=>api.get('/inventory/warehouses').then(r=>r.data)});
  const {data:products=[]}=useQuery<any[]>({queryKey:['purchase-products'],queryFn:()=>api.get('/catalog/products?limit=500').then(r=>r.data)});
  const variants=(Array.isArray(products)?products:[]).flatMap((p:any)=>(p.variants||[]).map((v:any)=>({...v,product_name:p.name})));const needle=search.toLowerCase();const found=variants.filter((v:any)=>!needle||[v.product_name,v.sku,v.barcode,v.size,v.color].some(x=>String(x||'').toLowerCase().includes(needle))).slice(0,80);const chosen:any[]=Object.values(lines);
  const subtotal=chosen.reduce((s,l)=>s+Number(l.quantity_ordered)*Number(l.unit_cost),0),vat=chosen.reduce((s,l)=>s+Number(l.quantity_ordered)*Number(l.unit_cost)*Number(l.tax_rate)/100,0),landed=Number(f.freight_amount||0)+Number(f.customs_amount||0)+Number(f.other_costs||0);
  const add=(v:any)=>setLines(x=>({...x,[v.id]:x[v.id]||{variant_id:v.id,product_name:v.product_name,sku:v.sku,size:v.size,color:v.color,quantity_ordered:1,unit_cost:Number(v.cost_price||0),tax_rate:15}}));
  const save=useMutation({mutationFn:()=>api.post('/purchasing/orders',{...f,lines:chosen}),onSuccess:()=>{qc.invalidateQueries({queryKey:['purchase-orders']});toast('Draft purchase order created');close()},onError:(e:any)=>toast(e.response?.data?.message||'Could not create PO','error')});
  return <Modal wide title="Create Purchase Order" sub="Select exact SKU/size/color variants and destination stock location" close={close} footer={<><div className="purch-footer-total"><span>Grand Total</span><b>{cash(subtotal+vat+landed)}</b></div><button className="btn-nx ghost" onClick={close}>Cancel</button><button className="btn-nx primary" disabled={!f.supplier_id||!f.warehouse_id||!chosen.length||save.isPending} onClick={()=>save.mutate()}>{save.isPending?'Creating…':`Create Draft PO (${chosen.length})`}</button></>}>
    <div className="purch-form-grid"><Field title="Supplier *"><select value={f.supplier_id} onChange={e=>setF((x:any)=>({...x,supplier_id:e.target.value}))}><option value="">Select supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field title="Destination Warehouse *"><select value={f.warehouse_id} onChange={e=>setF((x:any)=>({...x,warehouse_id:e.target.value}))}><option value="">Select warehouse</option>{warehouses.filter(w=>w.is_active!==false).map(w=><option key={w.id} value={w.id}>{w.name} · {w.code}</option>)}</select></Field><Field title="Expected Delivery"><input type="date" value={f.expected_date} onChange={e=>setF((x:any)=>({...x,expected_date:e.target.value}))}/></Field><Field title="Notes"><input value={f.notes} onChange={e=>setF((x:any)=>({...x,notes:e.target.value}))}/></Field></div>
    <div className="po-builder"><section><h3>Find Products</h3><div className="po-search"><i className="ti ti-search"/><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Scan barcode or search product, SKU, size, color…"/></div><div className="po-results">{found.map((v:any)=><button key={v.id} disabled={Boolean(lines[v.id])} onClick={()=>add(v)}><span><b>{v.product_name}</b><small>{v.sku||v.barcode}{v.size?` · ${v.size}`:''}{v.color?` · ${v.color}`:''}</small></span><em>{cash(v.cost_price)} cost</em><i className={`ti ${lines[v.id]?'ti-check':'ti-plus'}`}/></button>)}</div></section><section><h3>Order Lines <small>{chosen.length} variants</small></h3><div className="po-lines">{!chosen.length?<div className="purch-empty">Add exact product variants from the left.</div>:chosen.map(l=><div key={l.variant_id}><span><b>{l.product_name}</b><small>{l.sku}{l.size?` · ${l.size}`:''}{l.color?` · ${l.color}`:''}</small></span><input title="Quantity" type="number" min="1" value={l.quantity_ordered} onChange={e=>setLines(x=>({...x,[l.variant_id]:{...x[l.variant_id],quantity_ordered:Number(e.target.value)}}))}/><input title="Unit cost" type="number" min="0" step=".01" value={l.unit_cost} onChange={e=>setLines(x=>({...x,[l.variant_id]:{...x[l.variant_id],unit_cost:Number(e.target.value)}}))}/><button onClick={()=>setLines(x=>{const n={...x};delete n[l.variant_id];return n})}><i className="ti ti-trash"/></button></div>)}</div></section></div>
    <div className="po-costs"><Field title="Freight"><input type="number" value={f.freight_amount} onChange={e=>setF((x:any)=>({...x,freight_amount:e.target.value}))}/></Field><Field title="Customs / Duty"><input type="number" value={f.customs_amount} onChange={e=>setF((x:any)=>({...x,customs_amount:e.target.value}))}/></Field><Field title="Other Landed Costs"><input type="number" value={f.other_costs} onChange={e=>setF((x:any)=>({...x,other_costs:e.target.value}))}/></Field><span><small>Subtotal</small><b>{cash(subtotal)}</b></span><span><small>VAT</small><b>{cash(vat)}</b></span></div>
  </Modal>;
}

function ReceiveModal({po,close}:any){
  const qc=useQueryClient(),{toast}=useToast();const {data}=useQuery<any>({queryKey:['purchase-order',po.id],queryFn:()=>api.get(`/purchasing/orders/${po.id}`).then(r=>r.data)});const [invoice,setInvoice]=useState('');const [notes,setNotes]=useState('');const [qty,setQty]=useState<Record<string,number>>({});
  const lines=data?.lines||[];const receiving=lines.map((l:any)=>({...l,quantity_received:Number(qty[l.id]||0)})).filter((l:any)=>l.quantity_received>0);
  const save=useMutation({mutationFn:()=>api.post('/purchasing/receive',{po_id:po.id,supplier_invoice:invoice,notes,lines:receiving.map((l:any)=>({po_line_id:l.id,variant_id:l.variant_id,quantity_received:l.quantity_received,unit_cost:Number(l.unit_cost)}))}),onSuccess:()=>{qc.invalidateQueries({queryKey:['purchase-orders']});qc.invalidateQueries({queryKey:['purchase-order',po.id]});toast('Goods receipt posted and stock updated');close()},onError:(e:any)=>toast(e.response?.data?.message||'Could not receive goods','error')});
  return <Modal wide title={`Receive ${po.po_number}`} sub="Enter actual quantities; partial receiving is supported" close={close} footer={<><button className="btn-nx ghost" onClick={close}>Cancel</button><button className="btn-nx primary" disabled={!receiving.length||save.isPending} onClick={()=>save.mutate()}>{save.isPending?'Posting GRN…':`Receive ${receiving.reduce((s:any,l:any)=>s+l.quantity_received,0)} Units`}</button></>}><div className="purch-form-grid"><Field title="Supplier Invoice Number"><input value={invoice} onChange={e=>setInvoice(e.target.value)} placeholder="Required for audit trail"/></Field><Field title="Receiving Notes"><input value={notes} onChange={e=>setNotes(e.target.value)}/></Field></div><div className="receive-table"><div className="head"><span>Product / Variant</span><span>Ordered</span><span>Previously</span><span>Remaining</span><span>Receive Now</span></div>{lines.map((l:any)=>{const remaining=Number(l.quantity_ordered)-Number(l.quantity_received);return <div key={l.id}><span><b>{l.product_name}</b><small>{l.sku}{l.size?` · ${l.size}`:''}{l.color?` · ${l.color}`:''}</small></span><b>{l.quantity_ordered}</b><b>{l.quantity_received}</b><b>{remaining}</b><input type="number" min="0" max={remaining} value={qty[l.id]||0} onChange={e=>setQty(x=>({...x,[l.id]:Math.min(remaining,Math.max(0,Number(e.target.value)))}))}/></div>})}</div></Modal>;
}

function PaymentModal({po,close}:any){const qc=useQueryClient(),{toast}=useToast();const outstanding=Number(po.total)-Number(po.paid_amount||0);const [f,setF]=useState({amount:String(outstanding),method:'bank',reference:'',notes:''});const save=useMutation({mutationFn:()=>api.post(`/purchasing/orders/${po.id}/payments`,{...f,amount:Number(f.amount)}),onSuccess:()=>{qc.invalidateQueries({queryKey:['purchase-orders']});qc.invalidateQueries({queryKey:['purchase-order',po.id]});toast('Supplier payment recorded');close()},onError:(e:any)=>toast(e.response?.data?.message||'Could not record payment','error')});return <Modal title="Record Supplier Payment" sub={`${po.po_number} · Outstanding ${cash(outstanding)}`} close={close} footer={<><button className="btn-nx ghost" onClick={close}>Cancel</button><button className="btn-nx primary" disabled={!Number(f.amount)||save.isPending} onClick={()=>save.mutate()}>Post Payment</button></>}><div className="purch-form-grid"><Field title="Amount"><input type="number" max={outstanding} value={f.amount} onChange={e=>setF(x=>({...x,amount:e.target.value}))}/></Field><Field title="Method"><select value={f.method} onChange={e=>setF(x=>({...x,method:e.target.value}))}>{['bank','cash','card','cheque'].map(x=><option key={x} value={x}>{label(x)}</option>)}</select></Field><Field title="Reference"><input value={f.reference} onChange={e=>setF(x=>({...x,reference:e.target.value}))}/></Field><Field title="Notes"><input value={f.notes} onChange={e=>setF(x=>({...x,notes:e.target.value}))}/></Field></div></Modal>}

function ReturnModal({po,close}:any){const qc=useQueryClient(),{toast}=useToast();const {data}=useQuery<any>({queryKey:['purchase-order',po.id],queryFn:()=>api.get(`/purchasing/orders/${po.id}`).then(r=>r.data)});const [reason,setReason]=useState('');const [credit,setCredit]=useState('');const [qty,setQty]=useState<Record<string,number>>({});const lines=(data?.lines||[]).filter((x:any)=>Number(x.quantity_received)>0);const returns=lines.map((l:any)=>({variant_id:l.variant_id,quantity:Number(qty[l.variant_id]||0)})).filter((x:any)=>x.quantity>0);const save=useMutation({mutationFn:()=>api.post(`/purchasing/orders/${po.id}/returns`,{reason,credit_note:credit,lines:returns}),onSuccess:()=>{qc.invalidateQueries({queryKey:['purchase-order',po.id]});qc.invalidateQueries({queryKey:['purchase-orders']});toast('Purchase return posted and stock reduced');close()},onError:(e:any)=>toast(e.response?.data?.message||'Could not post return','error')});return <Modal title="Return Goods to Supplier" sub="Stock will be removed from the PO destination warehouse" close={close} footer={<><button className="btn-nx ghost" onClick={close}>Cancel</button><button className="btn-nx primary" disabled={!returns.length||save.isPending} onClick={()=>save.mutate()}>Post Purchase Return</button></>}><div className="purch-form-grid"><Field title="Reason"><input value={reason} onChange={e=>setReason(e.target.value)}/></Field><Field title="Supplier Credit Note"><input value={credit} onChange={e=>setCredit(e.target.value)}/></Field></div><div className="return-lines">{lines.map((l:any)=><label key={l.id}><span><b>{l.product_name}</b><small>{l.sku} · Received {l.quantity_received}</small></span><input type="number" min="0" max={l.quantity_received} value={qty[l.variant_id]||0} onChange={e=>setQty(x=>({...x,[l.variant_id]:Math.min(Number(l.quantity_received),Number(e.target.value))}))}/></label>)}</div></Modal>}

function Detail({order,close,approve,receive,pay,returns}:any){const {data}=useQuery<any>({queryKey:['purchase-order',order.id],queryFn:()=>api.get(`/purchasing/orders/${order.id}`).then(r=>r.data)});const d=data||order,lines=d.lines||[];return <aside className="purch-detail"><header><div><h2>{d.po_number}</h2><p>{d.supplier_name} · {d.warehouse_name}</p></div><button onClick={close}><i className="ti ti-x"/></button></header><div className="purch-detail-body"><div className="purch-detail-status"><span className={`nx-badge ${tone[d.status]||'grey'}`}>{label(d.status)}</span><span className={`nx-badge ${d.payment_status==='paid'?'active':d.payment_status==='partial'?'pending':'danger'}`}>{label(d.payment_status||'unpaid')}</span></div><div className="purch-detail-totals"><span><small>Subtotal</small><b>{cash(d.subtotal)}</b></span><span><small>VAT</small><b>{cash(d.tax_amount)}</b></span><span><small>Landed Cost</small><b>{cash(Number(d.freight_amount||0)+Number(d.customs_amount||0)+Number(d.other_costs||0))}</b></span><span><small>Grand Total</small><b>{cash(d.total)}</b></span><span><small>Paid</small><b>{cash(d.paid_amount)}</b></span><span><small>Outstanding</small><b>{cash(Number(d.total)-Number(d.paid_amount||0))}</b></span></div><h3>Order Lines</h3><div className="purch-detail-lines">{lines.map((l:any)=><div key={l.id}><span><b>{l.product_name}</b><small>{l.sku}{l.size?` · ${l.size}`:''}{l.color?` · ${l.color}`:''}</small></span><em><b>{l.quantity_received}/{l.quantity_ordered}</b><small>{cash(l.unit_cost)} each</small></em></div>)}</div>{d.receipts?.length>0&&<><h3>Goods Receipts</h3>{d.receipts.map((x:any)=><div className="purch-history" key={x.id}><i className="ti ti-package-import"/><span><b>{x.grn_number}</b><small>{x.supplier_invoice||'No supplier invoice'} · {new Date(x.received_at).toLocaleDateString()}</small></span></div>)}</>}</div><footer>{d.status==='draft'&&<button className="btn-nx primary" onClick={approve}>Approve PO</button>}{['approved','partially_received'].includes(d.status)&&<button className="btn-nx primary" onClick={receive}>Receive Goods</button>}{d.status!=='cancelled'&&d.payment_status!=='paid'&&<button className="btn-nx ghost" onClick={pay}>Record Payment</button>}{['received','partially_received'].includes(d.status)&&<button className="btn-nx ghost" onClick={returns}>Return Goods</button>}</footer></aside>}

export default function Purchasing(){
  const qc=useQueryClient(),{toast}=useToast();const [tab,setTab]=useState('orders'),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[selected,setSelected]=useState<any>(null),[modal,setModal]=useState(''),[supplier,setSupplier]=useState<any>(null);
  const {data:orders=[],isLoading}=useQuery<any[]>({queryKey:['purchase-orders'],queryFn:()=>api.get('/purchasing/orders').then(r=>r.data)});const {data:suppliers=[]}=useQuery<any[]>({queryKey:['suppliers'],queryFn:()=>api.get('/purchasing/suppliers').then(r=>r.data)});
  const shown=useMemo(()=>orders.filter(o=>(filter==='all'||o.status===filter)&&(!search||[o.po_number,o.supplier_name,o.warehouse_name].some(v=>String(v||'').toLowerCase().includes(search.toLowerCase())))),[orders,filter,search]);const total=orders.filter(x=>x.status!=='cancelled').reduce((s,x)=>s+Number(x.total||0),0),outstanding=orders.filter(x=>x.status!=='cancelled').reduce((s,x)=>s+Math.max(0,Number(x.total)-Number(x.paid_amount||0)),0);
  const approve=useMutation({mutationFn:(id:string)=>api.patch(`/purchasing/orders/${id}/approve`),onSuccess:()=>{qc.invalidateQueries({queryKey:['purchase-orders']});qc.invalidateQueries({queryKey:['purchase-order',selected?.id]});toast('Purchase order approved')},onError:(e:any)=>toast(e.response?.data?.message||'Could not approve','error')});
  return <div className="purch-page"><div className="nx-page-head"><div><h1 className="nx-page-title">Purchasing Control Center</h1><p className="nx-page-sub">Purchase orders, receiving, supplier invoices, payments and returns</p></div><div><button className="btn-nx ghost" onClick={()=>{setSupplier(null);setModal('supplier')}}><i className="ti ti-user-plus"/> Supplier</button><button className="btn-nx primary" onClick={()=>setModal('po')}><i className="ti ti-plus"/> New Purchase Order</button></div></div>
    <div className="nx-stats cols-4"><div className="nx-stat"><div className="nx-stat-icon indigo"><i className="ti ti-file-invoice"/></div><div className="nx-stat-body"><div className="nx-stat-val">{orders.length}</div><div className="nx-stat-lbl">Purchase Orders</div></div></div><div className="nx-stat"><div className="nx-stat-icon amber"><i className="ti ti-truck-delivery"/></div><div className="nx-stat-body"><div className="nx-stat-val">{orders.filter(x=>['approved','partially_received'].includes(x.status)).length}</div><div className="nx-stat-lbl">Awaiting Receipt</div></div></div><div className="nx-stat"><div className="nx-stat-icon green"><i className="ti ti-cash"/></div><div className="nx-stat-body"><div className="nx-stat-val">{cash(total)}</div><div className="nx-stat-lbl">Purchase Value</div></div></div><div className="nx-stat"><div className="nx-stat-icon red"><i className="ti ti-clock-dollar"/></div><div className="nx-stat-body"><div className="nx-stat-val">{cash(outstanding)}</div><div className="nx-stat-lbl">Supplier Payable</div></div></div></div>
    <div className="nx-tabs">{[['orders','Purchase Orders'],['suppliers','Suppliers']].map(([id,x])=><button className={`nx-tab ${tab===id?'on':''}`} key={id} onClick={()=>setTab(id)}>{x}</button>)}</div>
    {tab==='orders'?<><div className="purch-toolbar"><div><i className="ti ti-search"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search PO, supplier or warehouse…"/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All statuses</option>{['draft','approved','partially_received','received','cancelled'].map(x=><option key={x} value={x}>{label(x)}</option>)}</select></div><div className={`purch-layout ${selected?'open':''}`}><div className="purch-table-wrap"><table><thead><tr><th>PO / Supplier</th><th>Destination</th><th>Ordered / Received</th><th>VAT</th><th>Total</th><th>Payment</th><th>Expected / Due</th><th>Status</th></tr></thead><tbody>{isLoading?<tr><td colSpan={8} className="purch-empty">Loading…</td></tr>:shown.map(o=><tr key={o.id} className={selected?.id===o.id?'selected':''} onClick={()=>setSelected(o)}><td><b>{o.po_number}</b><small>{o.supplier_name}</small></td><td><b>{o.warehouse_name}</b><small>{o.items_count} variants</small></td><td><b>{o.received_units}/{o.ordered_units} units</b></td><td><b>{cash(o.tax_amount)}</b></td><td><b>{cash(o.total)}</b></td><td><span className={`nx-badge ${o.payment_status==='paid'?'active':o.payment_status==='partial'?'pending':'danger'}`}>{label(o.payment_status||'unpaid')}</span><small>{cash(Number(o.total)-Number(o.paid_amount||0))} due</small></td><td><b>{o.expected_date?new Date(o.expected_date).toLocaleDateString():'—'}</b><small>Due {o.due_date?new Date(o.due_date).toLocaleDateString():'—'}</small></td><td><span className={`nx-badge ${tone[o.status]||'grey'}`}>{label(o.status)}</span></td></tr>)}</tbody></table></div>{selected&&<Detail order={selected} close={()=>setSelected(null)} approve={()=>approve.mutate(selected.id)} receive={()=>setModal('receive')} pay={()=>setModal('payment')} returns={()=>setModal('return')}/>}</div></>:<div className="supplier-list">{suppliers.map(s=><article key={s.id}><header><span><i className="ti ti-building-store"/></span><div><h3>{s.name}</h3><p>{s.code||'No code'} · {s.city||'City not set'}</p></div><button onClick={()=>{setSupplier(s);setModal('supplier')}}><i className="ti ti-edit"/></button></header><div><span><small>Orders</small><b>{s.order_count}</b></span><span><small>Lifetime Purchases</small><b>{cash(s.lifetime_purchases)}</b></span><span><small>Outstanding</small><b>{cash(s.outstanding)}</b></span></div><footer><span><i className="ti ti-phone"/> {s.phone||'Not set'}</span><span>Net {s.payment_terms||0} days</span></footer></article>)}</div>}
    {modal==='supplier'&&<SupplierModal supplier={supplier} close={()=>setModal('')}/>} {modal==='po'&&<POModal close={()=>setModal('')}/>} {modal==='receive'&&selected&&<ReceiveModal po={selected} close={()=>setModal('')}/>} {modal==='payment'&&selected&&<PaymentModal po={selected} close={()=>setModal('')}/>} {modal==='return'&&selected&&<ReturnModal po={selected} close={()=>setModal('')}/>}
  </div>;
}
