import { useEffect,useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import api from '../../lib/api';
import { useToast } from '../../components/Toast';
import { getErr } from '../../lib/err';

const SECTIONS=[['general','General','ti-settings'],['branches','Branches','ti-building-store'],['taxes','Taxes & VAT','ti-receipt-tax'],['payment','Payment Methods','ti-credit-card'],['pos','POS & Inventory','ti-device-desktop'],['ecommerce','E-commerce','ti-world'],['users','Users & Roles','ti-users-group'],['notifications','Approvals & Alerts','ti-bell'],['integrations','Integrations','ti-plug'],['security','Security & Audit','ti-shield-lock']] as const;
const nav=(s:string)=>window.dispatchEvent(new CustomEvent('nav',{detail:s}));
export default function Settings(){
 const [sec,setSec]=useState('general');const [form,setForm]=useState<any>({});const {toast}=useToast();const qc=useQueryClient();
 const {data,isLoading}=useQuery({queryKey:['company-settings'],queryFn:()=>api.get('/settings').then(r=>r.data)});
 useEffect(()=>{if(data)setForm(data)},[data]);
 const save=useMutation({mutationFn:()=>api.patch('/settings',form),onSuccess:r=>{setForm(r.data);qc.setQueryData(['company-settings'],r.data);toast('Settings saved successfully','success')},onError:(e:any)=>toast(getErr(e),'error')});
 const set=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}));
 if(isLoading)return <div className="nx-card" style={{padding:40,textAlign:'center'}}>Loading company settings…</div>;
 return <div><div className="nx-page-head"><div><h1 className="nx-page-title">Settings</h1><p className="nx-page-sub">Company-wide ERP, POS and online store configuration</p></div><button className="btn-nx primary" disabled={save.isPending} onClick={()=>save.mutate()}><i className="ti ti-device-floppy"/> {save.isPending?'Saving…':'Save Changes'}</button></div>
 <div style={{display:'grid',gridTemplateColumns:'240px minmax(0,1fr)',gap:20,alignItems:'start'}}><aside className="nx-card" style={{padding:8}}>{SECTIONS.map(([id,label,icon])=><button key={id} onClick={()=>setSec(id)} style={{width:'100%',display:'flex',alignItems:'center',gap:10,padding:'11px 12px',border:'none',borderRadius:9,cursor:'pointer',textAlign:'left',fontSize:13.5,background:sec===id?'var(--canvas)':'none',color:sec===id?'var(--accent)':'var(--muted)',fontWeight:sec===id?700:500}}><i className={`ti ${icon}`}/>{label}</button>)}</aside>
 <main className="nx-card" style={{padding:24}}><h3 style={{fontWeight:750,fontSize:18,marginBottom:4}}>{SECTIONS.find(x=>x[0]===sec)?.[1]}</h3><p style={{color:'var(--muted)',fontSize:13,marginBottom:22}}>Changes apply company-wide unless managed from the Branches module.</p>
 {sec==='general'&&<Grid><Field l="Business name" k="business_name" f={form} set={set}/><Field l="Arabic business name" k="business_name_ar" f={form} set={set} rtl/><Field l="VAT number" k="vat_number" f={form} set={set}/><Field l="CR number" k="cr_number" f={form} set={set}/><Field l="Business phone" k="phone" f={form} set={set}/><Field l="Business email" k="email" type="email" f={form} set={set}/><Field l="Address" k="address" f={form} set={set}/><Field l="Arabic address" k="address_ar" f={form} set={set} rtl/><Field l="Logo URL" k="logo_url" f={form} set={set}/><Select l="Currency" k="currency" f={form} set={set} opts={['SAR']}/><Select l="Timezone" k="timezone" f={form} set={set} opts={['Asia/Riyadh']}/><Select l="Default language" k="language" f={form} set={set} opts={['en','ar']}/></Grid>}
 {sec==='branches'&&<Action title="Branch configuration" text="Add branches, assign POS employees, payment accounts, partners and branch finance from the dedicated control center." icon="ti-building-store" button="Open Branch Management" go={()=>nav('ad-branches')}/>}
 {sec==='taxes'&&<Grid><Field l="VAT rate %" k="vat_rate" type="number" f={form} set={set}/><Field l="Invoice prefix" k="invoice_prefix" f={form} set={set}/><Toggle l="Prices include VAT" k="prices_include_vat" f={form} set={set}/><Toggle l="ZATCA invoices enabled" k="zatca_enabled" f={form} set={set}/><Toggle l="Simplified tax invoice" k="simplified_invoice" f={form} set={set}/><Field l="Receipt / invoice footer" k="invoice_footer" f={form} set={set}/><Action title="ZATCA compliance workspace" text="Review invoice compliance, VAT totals and reporting status." icon="ti-file-check" button="Open ZATCA" go={()=>nav('ad-zatca')}/></Grid>}
 {sec==='payment'&&<Grid><Toggle l="Cash" k="cash_enabled" f={form} set={set}/><Toggle l="Mada" k="mada_enabled" f={form} set={set}/><Toggle l="Visa / Mastercard" k="card_enabled" f={form} set={set}/><Toggle l="Tabby" k="tabby_enabled" f={form} set={set}/><Toggle l="Tamara" k="tamara_enabled" f={form} set={set}/><Toggle l="Bank transfer" k="bank_transfer_enabled" f={form} set={set}/><Toggle l="Cash on delivery" k="cod_enabled" f={form} set={set}/><Field l="Mada commission %" k="mada_commission" type="number" f={form} set={set}/><Field l="Card commission %" k="card_commission" type="number" f={form} set={set}/><Field l="Tabby commission %" k="tabby_commission" type="number" f={form} set={set}/><Field l="Tamara commission %" k="tamara_commission" type="number" f={form} set={set}/></Grid>}
 {sec==='pos'&&<Grid><Toggle l="Allow negative stock sale" k="negative_stock_allowed" f={form} set={set}/><Toggle l="Customer required before payment" k="require_customer" f={form} set={set}/><Toggle l="Allow split payment" k="allow_split_payment" f={form} set={set}/><Toggle l="Allow order discount" k="allow_discount" f={form} set={set}/><Field l="Maximum discount %" k="max_discount_percent" type="number" f={form} set={set}/><Select l="Receipt paper" k="receipt_size" f={form} set={set} opts={['80mm','58mm','A4']}/><Toggle l="Auto print receipt" k="auto_print_receipt" f={form} set={set}/><Select l="Barcode format" k="barcode_format" f={form} set={set} opts={['CODE128','EAN13']}/><Field l="Default low-stock level" k="low_stock_threshold" type="number" f={form} set={set}/></Grid>}
 {sec==='ecommerce'&&<Grid><Toggle l="Online store active" k="store_enabled" f={form} set={set}/><Toggle l="Guest checkout" k="guest_checkout" f={form} set={set}/><Field l="Delivery fee (SAR)" k="default_delivery_fee" type="number" f={form} set={set}/><Field l="Free delivery from (SAR)" k="free_delivery_from" type="number" f={form} set={set}/><Field l="Delivery estimate" k="delivery_estimate" f={form} set={set}/><Field l="Return period (days)" k="return_days" type="number" f={form} set={set}/><Field l="Online stock safety buffer" k="online_stock_buffer" type="number" f={form} set={set}/><Action title="Store content management" text="Manage banners, homepage sections, promotions, delivery messaging and SEO." icon="ti-world-cog" button="Open E-commerce Admin" go={()=>nav('ad-ecom')}/></Grid>}
 {sec==='users'&&<><Action title="Employees and payroll" text="Create employees before assigning branch POS access." icon="ti-id" button="Open HR & Payroll" go={()=>nav('ad-hr')}/><div style={{height:14}}/><Action title="Branch POS access" text="Assign active employees to their branch and create secure POS login credentials." icon="ti-users-group" button="Assign POS Users" go={()=>nav('ad-branches')}/></>}
 {sec==='notifications'&&<Grid><Toggle l="Stock transfer approval" k="stock_transfer_approval" f={form} set={set}/><Toggle l="Purchase approval" k="purchase_approval" f={form} set={set}/><Toggle l="Expense approval" k="expense_approval" f={form} set={set}/><Toggle l="Email notifications" k="email_notifications" f={form} set={set}/><Toggle l="Low-stock alerts" k="low_stock_alerts" f={form} set={set}/><Toggle l="Daily sales summary" k="daily_sales_summary" f={form} set={set}/></Grid>}
 {sec==='integrations'&&<Grid><Field l="WhatsApp number" k="whatsapp_number" f={form} set={set}/><Field l="Outgoing email" k="smtp_from_email" type="email" f={form} set={set}/><Field l="Google Analytics ID" k="google_analytics_id" f={form} set={set}/><Field l="Meta Pixel ID" k="meta_pixel_id" f={form} set={set}/><Field l="Webhook URL" k="webhook_url" f={form} set={set}/></Grid>}
 {sec==='security'&&<Grid><Toggle l="Audit log enabled" k="audit_log_enabled" f={form} set={set}/><Field l="Session timeout (minutes)" k="session_timeout_minutes" type="number" f={form} set={set}/><div style={{gridColumn:'1/-1',padding:16,border:'1px solid var(--line)',borderRadius:12,color:'var(--muted)',fontSize:13}}><b style={{color:'var(--text)'}}>Protected configuration</b><br/>Settings are isolated by company, require authenticated administrator access and record the last updating user and time.</div></Grid>}
 </main></div></div>
}
function Grid({children}:{children:any}){return <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:16}}>{children}</div>}
function Field({l,k,f,set,type='text',rtl=false}:{l:string;k:string;f:any;set:any;type?:string;rtl?:boolean}){return <label style={labelStyle}>{l}<input dir={rtl?'rtl':undefined} className="nx-input" style={{width:'100%'}} type={type} step={type==='number'?'0.01':undefined} value={f[k]??''} onChange={e=>set(k,type==='number'?Number(e.target.value):e.target.value)}/></label>}
function Select({l,k,f,set,opts}:{l:string;k:string;f:any;set:any;opts:string[]}){return <label style={labelStyle}>{l}<select className="nx-input" style={{width:'100%'}} value={f[k]??opts[0]} onChange={e=>set(k,e.target.value)}>{opts.map(x=><option key={x}>{x}</option>)}</select></label>}
function Toggle({l,k,f,set}:{l:string;k:string;f:any;set:any}){return <label style={{...labelStyle,display:'flex',alignItems:'center',justifyContent:'space-between',minHeight:48,padding:'10px 13px',border:'1px solid var(--line)',borderRadius:11}}><span>{l}</span><input type="checkbox" checked={f[k]===true} onChange={e=>set(k,e.target.checked)} style={{width:18,height:18,accentColor:'var(--accent)'}}/></label>}
function Action({title,text,icon,button,go}:{title:string;text:string;icon:string;button:string;go:()=>void}){return <div style={{gridColumn:'1/-1',display:'flex',alignItems:'center',gap:16,padding:18,border:'1px solid var(--line)',borderRadius:13,background:'var(--canvas)'}}><i className={`ti ${icon}`} style={{fontSize:28,color:'var(--accent)'}}/><div style={{flex:1}}><b>{title}</b><p style={{fontSize:13,color:'var(--muted)',marginTop:3}}>{text}</p></div><button className="btn-nx ghost" onClick={go}>{button}<i className="ti ti-arrow-right"/></button></div>}
const labelStyle:any={display:'flex',flexDirection:'column',gap:6,fontSize:12.5,fontWeight:650,color:'var(--muted)'};
