import { BadRequestException, Injectable, NotFoundException, OnModuleInit } from '@nestjs/common';
import { DatabaseService } from '../database/database.service';
import { randomUUID } from 'crypto';
@Injectable()
export class B2bService implements OnModuleInit {
  constructor(private db:DatabaseService){}
  async onModuleInit(){await this.db.query(`
    ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS wholesale_price numeric(14,2);
    CREATE TABLE IF NOT EXISTS b2b_orders(id uuid PRIMARY KEY,company_id uuid NOT NULL REFERENCES companies(id),order_number varchar(60) NOT NULL,
      customer_id uuid REFERENCES customers(id),warehouse_id uuid NOT NULL REFERENCES warehouses(id),business_name varchar(180) NOT NULL,
      contact_name varchar(160),phone varchar(40),email varchar(180),vat_number varchar(40),cr_number varchar(50),billing_address text,
      shipping_address text,status varchar(30) NOT NULL DEFAULT 'quotation',payment_status varchar(30) NOT NULL DEFAULT 'unpaid',
      payment_terms varchar(40) NOT NULL DEFAULT 'cash',credit_days integer NOT NULL DEFAULT 0,due_date date,
      subtotal numeric(14,2) NOT NULL DEFAULT 0,discount_amount numeric(14,2) NOT NULL DEFAULT 0,tax_amount numeric(14,2) NOT NULL DEFAULT 0,
      total numeric(14,2) NOT NULL DEFAULT 0,amount_paid numeric(14,2) NOT NULL DEFAULT 0,balance_due numeric(14,2) NOT NULL DEFAULT 0,
      customer_po varchar(80),notes text,created_by uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,order_number));
    CREATE TABLE IF NOT EXISTS b2b_order_lines(id uuid PRIMARY KEY,order_id uuid NOT NULL REFERENCES b2b_orders(id) ON DELETE CASCADE,
      variant_id uuid NOT NULL REFERENCES product_variants(id),quantity integer NOT NULL,unit_price numeric(14,2) NOT NULL,
      discount_percent numeric(7,3) NOT NULL DEFAULT 0,discount_amount numeric(14,2) NOT NULL DEFAULT 0,line_total numeric(14,2) NOT NULL);
    CREATE TABLE IF NOT EXISTS b2b_payments(id uuid PRIMARY KEY,order_id uuid NOT NULL REFERENCES b2b_orders(id) ON DELETE CASCADE,
      method varchar(40) NOT NULL,amount numeric(14,2) NOT NULL,reference varchar(100),notes text,received_by uuid REFERENCES users(id),
      received_at timestamptz NOT NULL DEFAULT now());
    CREATE INDEX IF NOT EXISTS idx_b2b_orders_company ON b2b_orders(company_id,created_at DESC);`)}
  async list(companyId:string,status?:string,search?:string){const p:any[]=[companyId],w=['o.company_id=$1'];if(status){p.push(status);w.push(`o.status=$${p.length}`)}if(search){p.push(`%${search}%`);w.push(`(o.order_number ILIKE $${p.length} OR o.business_name ILIKE $${p.length} OR o.phone ILIKE $${p.length})`)}
    const orders=await this.db.query(`SELECT o.*,w.name warehouse_name,COALESCE((SELECT SUM(l.quantity) FROM b2b_order_lines l WHERE l.order_id=o.id),0)::int total_qty FROM b2b_orders o JOIN warehouses w ON w.id=o.warehouse_id WHERE ${w.join(' AND ')} ORDER BY o.created_at DESC LIMIT 300`,p);
    const summary=await this.db.query(`SELECT COUNT(*)::int orders,COALESCE(SUM(total),0) sales,COALESCE(SUM(balance_due),0) receivables,COUNT(*) FILTER(WHERE due_date<CURRENT_DATE AND balance_due>0)::int overdue FROM b2b_orders WHERE company_id=$1 AND status NOT IN ('cancelled','quotation')`,[companyId]);return{orders:orders.rows,summary:summary.rows[0]}}
  async detail(companyId:string,id:string){const o=await this.db.query(`SELECT o.*,w.name warehouse_name FROM b2b_orders o JOIN warehouses w ON w.id=o.warehouse_id WHERE o.id=$1 AND o.company_id=$2`,[id,companyId]);if(!o.rows[0])throw new NotFoundException('B2B order not found');
    const l=await this.db.query(`SELECT l.*,p.name product_name,v.sku,v.barcode,v.size,v.color FROM b2b_order_lines l JOIN product_variants v ON v.id=l.variant_id JOIN products p ON p.id=v.product_id WHERE l.order_id=$1`,[id]);const pay=await this.db.query(`SELECT * FROM b2b_payments WHERE order_id=$1 ORDER BY received_at DESC`,[id]);return{...o.rows[0],lines:l.rows,payments:pay.rows}}
  async catalog(companyId:string,warehouseId:string,search?:string){if(!warehouseId)throw new BadRequestException('Select a warehouse');const p:any[]=[companyId,warehouseId];let s='';if(search){p.push(`%${search}%`);s=`AND (p.name ILIKE $3 OR v.sku ILIKE $3 OR v.barcode ILIKE $3 OR v.color ILIKE $3 OR v.size ILIKE $3)`}
    return(await this.db.query(`SELECT v.id variant_id,p.name product_name,v.sku,v.barcode,v.size,v.color,v.selling_price retail_price,COALESCE(v.wholesale_price,v.selling_price) wholesale_price,COALESCE(i.quantity-i.reserved_quantity,0)::int available FROM product_variants v JOIN products p ON p.id=v.product_id LEFT JOIN inventory i ON i.variant_id=v.id AND i.warehouse_id=$2 WHERE p.company_id=$1 AND p.is_active=true AND p.deleted_at IS NULL ${s} ORDER BY p.name,v.size,v.color LIMIT 100`,p)).rows}
  async create(companyId:string,userId:string,b:any){if(!b.warehouse_id||!String(b.business_name||'').trim())throw new BadRequestException('Warehouse and business customer are required');if(!Array.isArray(b.lines)||!b.lines.length)throw new BadRequestException('Add at least one product');
    const lines=b.lines.map((x:any)=>{const q=Math.floor(Number(x.quantity)),price=Number(x.unit_price),pct=Math.max(0,Math.min(100,Number(x.discount_percent||0)));if(!x.variant_id||q<=0||price<0)throw new BadRequestException('Invalid order line');const gross=q*price,d=gross*pct/100;return{...x,quantity:q,unit_price:price,discount_percent:pct,discount_amount:d,line_total:gross-d}});
    const subtotal=lines.reduce((s:number,x:any)=>s+x.quantity*x.unit_price,0),discount=lines.reduce((s:number,x:any)=>s+x.discount_amount,0),taxable=subtotal-discount,tax=taxable*.15,total=taxable+tax,id=randomUUID(),number=`B2B-${Date.now()}`;
    return this.db.transaction(async c=>{const wh=await c.query(`SELECT id FROM warehouses WHERE id=$1 AND company_id=$2 AND COALESCE(is_active,true)=true`,[b.warehouse_id,companyId]);if(!wh.rows[0])throw new BadRequestException('Warehouse is invalid');
      const o=await c.query(`INSERT INTO b2b_orders(id,company_id,order_number,customer_id,warehouse_id,business_name,contact_name,phone,email,vat_number,cr_number,billing_address,shipping_address,status,payment_terms,credit_days,due_date,subtotal,discount_amount,tax_amount,total,balance_due,customer_po,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'quotation',$14,$15,$16,$17,$18,$19,$20,$20,$21,$22,$23) RETURNING *`,[id,companyId,number,b.customer_id||null,b.warehouse_id,String(b.business_name).trim(),b.contact_name||null,b.phone||null,b.email||null,b.vat_number||null,b.cr_number||null,b.billing_address||null,b.shipping_address||null,b.payment_terms||'cash',Number(b.credit_days||0),b.due_date||null,subtotal,discount,tax,total,b.customer_po||null,b.notes||null,userId]);
      for(const x of lines)await c.query(`INSERT INTO b2b_order_lines(id,order_id,variant_id,quantity,unit_price,discount_percent,discount_amount,line_total) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[randomUUID(),id,x.variant_id,x.quantity,x.unit_price,x.discount_percent,x.discount_amount,x.line_total]);return o.rows[0]})}
  async changeStatus(companyId:string,userId:string,id:string,status:string){if(!['confirmed','delivered','cancelled'].includes(status))throw new BadRequestException('Invalid status');return this.db.transaction(async c=>{const r=await c.query(`SELECT * FROM b2b_orders WHERE id=$1 AND company_id=$2 FOR UPDATE`,[id,companyId]),o=r.rows[0];if(!o)throw new NotFoundException('B2B order not found');const lines=await c.query(`SELECT * FROM b2b_order_lines WHERE order_id=$1`,[id]);
    if(status==='confirmed'){if(o.status!=='quotation')throw new BadRequestException('Only quotations can be confirmed');for(const x of lines.rows){const st=await c.query(`SELECT quantity,reserved_quantity FROM inventory WHERE warehouse_id=$1 AND variant_id=$2 FOR UPDATE`,[o.warehouse_id,x.variant_id]);if(Number(st.rows[0]?.quantity||0)-Number(st.rows[0]?.reserved_quantity||0)<Number(x.quantity))throw new BadRequestException('Insufficient stock');await c.query(`UPDATE inventory SET reserved_quantity=reserved_quantity+$1,updated_at=NOW() WHERE warehouse_id=$2 AND variant_id=$3`,[x.quantity,o.warehouse_id,x.variant_id])}}
    if(status==='delivered'){if(o.status!=='confirmed')throw new BadRequestException('Confirm order before delivery');for(const x of lines.rows){const st=await c.query(`UPDATE inventory SET quantity=quantity-$1,reserved_quantity=GREATEST(0,reserved_quantity-$1),updated_at=NOW() WHERE warehouse_id=$2 AND variant_id=$3 RETURNING quantity`,[x.quantity,o.warehouse_id,x.variant_id]);await c.query(`INSERT INTO stock_movements(warehouse_id,variant_id,movement_type,quantity,quantity_before,quantity_after,reason,created_by) VALUES($1,$2,'b2b_sale',$3,$4,$5,$6,$7)`,[o.warehouse_id,x.variant_id,-Number(x.quantity),Number(st.rows[0].quantity)+Number(x.quantity),st.rows[0].quantity,o.order_number,userId])}}
    if(status==='cancelled'&&o.status==='confirmed')for(const x of lines.rows)await c.query(`UPDATE inventory SET reserved_quantity=GREATEST(0,reserved_quantity-$1),updated_at=NOW() WHERE warehouse_id=$2 AND variant_id=$3`,[x.quantity,o.warehouse_id,x.variant_id]);return(await c.query(`UPDATE b2b_orders SET status=$1,updated_at=NOW() WHERE id=$2 RETURNING *`,[status,id])).rows[0]})}
  async addPayment(companyId:string,userId:string,id:string,b:any){const amount=Number(b.amount);if(!Number.isFinite(amount)||amount<=0)throw new BadRequestException('Enter valid payment');return this.db.transaction(async c=>{const r=await c.query(`SELECT * FROM b2b_orders WHERE id=$1 AND company_id=$2 AND status<>'cancelled' FOR UPDATE`,[id,companyId]),o=r.rows[0];if(!o)throw new NotFoundException('B2B order not found');if(amount>Number(o.balance_due)+.01)throw new BadRequestException('Payment exceeds balance');await c.query(`INSERT INTO b2b_payments(id,order_id,method,amount,reference,notes,received_by) VALUES($1,$2,$3,$4,$5,$6,$7)`,[randomUUID(),id,b.method||'bank_transfer',amount,b.reference||null,b.notes||null,userId]);const paid=Number(o.amount_paid)+amount,balance=Math.max(0,Number(o.total)-paid);return(await c.query(`UPDATE b2b_orders SET amount_paid=$1,balance_due=$2,payment_status=$3,updated_at=NOW() WHERE id=$4 RETURNING *`,[paid,balance,balance<=.01?'paid':'partial',id])).rows[0]})}
}
