import { BadRequestException, Injectable, NotFoundException, OnModuleInit } from '@nestjs/common';
import { randomUUID } from 'crypto';
import { DatabaseService } from '../database/database.service';

@Injectable()
export class ExpensesService implements OnModuleInit {
  constructor(private db:DatabaseService){}
  async onModuleInit(){
    await this.db.query(`CREATE TABLE IF NOT EXISTS expense_management_categories(
      id UUID PRIMARY KEY,company_id UUID NOT NULL REFERENCES companies(id),name VARCHAR(100) NOT NULL,
      code VARCHAR(30),type VARCHAR(30) NOT NULL DEFAULT 'operating',budget_monthly NUMERIC(16,2) NOT NULL DEFAULT 0,
      active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(company_id,name))`);
    await this.db.query(`CREATE TABLE IF NOT EXISTS expense_management_records(
      id UUID PRIMARY KEY,company_id UUID NOT NULL REFERENCES companies(id),expense_number VARCHAR(50) NOT NULL,
      type VARCHAR(30) NOT NULL DEFAULT 'general',category_id UUID REFERENCES expense_management_categories(id),
      branch_id UUID REFERENCES branches(id),supplier_id UUID REFERENCES suppliers(id),purchase_order_id UUID REFERENCES purchase_orders(id),
      employee_name VARCHAR(160),vendor VARCHAR(160),description TEXT NOT NULL,expense_date DATE NOT NULL,due_date DATE,
      subtotal NUMERIC(16,2) NOT NULL DEFAULT 0,vat_amount NUMERIC(16,2) NOT NULL DEFAULT 0,total NUMERIC(16,2) NOT NULL DEFAULT 0,
      paid_amount NUMERIC(16,2) NOT NULL DEFAULT 0,payment_method VARCHAR(40),payment_status VARCHAR(20) NOT NULL DEFAULT 'unpaid',
      status VARCHAR(20) NOT NULL DEFAULT 'draft',recurring_frequency VARCHAR(20),next_run_date DATE,
      reference VARCHAR(120),receipt_url TEXT,notes TEXT,created_by UUID REFERENCES users(id),approved_by UUID REFERENCES users(id),
      approved_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      UNIQUE(company_id,expense_number))`);
    await this.db.query(`CREATE TABLE IF NOT EXISTS expense_management_payments(
      id UUID PRIMARY KEY,company_id UUID NOT NULL REFERENCES companies(id),expense_id UUID NOT NULL REFERENCES expense_management_records(id) ON DELETE CASCADE,
      amount NUMERIC(16,2) NOT NULL CHECK(amount>0),method VARCHAR(40) NOT NULL,reference VARCHAR(120),notes TEXT,
      paid_by UUID REFERENCES users(id),paid_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await this.db.query(`CREATE TABLE IF NOT EXISTS expense_management_activity(
      id UUID PRIMARY KEY,company_id UUID NOT NULL REFERENCES companies(id),expense_id UUID NOT NULL REFERENCES expense_management_records(id) ON DELETE CASCADE,
      action VARCHAR(40) NOT NULL,comment TEXT,actor_id UUID REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
    await this.db.query(`CREATE INDEX IF NOT EXISTS idx_expense_mgmt_company_date ON expense_management_records(company_id,expense_date DESC)`);
    await this.db.query(`CREATE INDEX IF NOT EXISTS idx_expense_mgmt_status ON expense_management_records(company_id,status,payment_status)`);
    for(const [name,code,type] of [['Rent & Lease','RENT','operating'],['Utilities','UTIL','operating'],['Marketing & Advertising','MKT','operating'],['Travel & Transport','TRVL','operating'],['Office & Supplies','OFF','operating'],['Repairs & Maintenance','R&M','operating'],['Professional Services','PRO','operating'],['Staff Reimbursement','REIM','reimbursement'],['Petty Cash','PETTY','petty_cash']])
      await this.db.query(`INSERT INTO expense_management_categories(id,company_id,name,code,type) SELECT $1,c.id,$2,$3,$4 FROM companies c WHERE NOT EXISTS(SELECT 1 FROM expense_management_categories x WHERE x.company_id=c.id AND x.name=$2)`,[randomUUID(),name,code,type]);
  }
  private dates(from?:string,to?:string){return [from||new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10),to||new Date().toISOString().slice(0,10)];}
  async dashboard(companyId:string,from?:string,to?:string){const [a,b]=this.dates(from,to);const summary=await this.db.query(`SELECT
    COALESCE(SUM(total) FILTER(WHERE expense_date BETWEEN $2 AND $3 AND status<>'rejected'),0)::numeric total_expenses,
    COALESCE(SUM(vat_amount) FILTER(WHERE expense_date BETWEEN $2 AND $3 AND status<>'rejected'),0)::numeric input_vat,
    COALESCE(SUM(total-paid_amount) FILTER(WHERE payment_status<>'paid' AND status='approved'),0)::numeric outstanding,
    COUNT(*) FILTER(WHERE status='pending')::int pending_approvals,
    COUNT(*) FILTER(WHERE due_date<CURRENT_DATE AND payment_status<>'paid' AND status='approved')::int overdue,
    COUNT(*) FILTER(WHERE recurring_frequency IS NOT NULL AND status<>'rejected')::int recurring
    FROM expense_management_records WHERE company_id=$1`,[companyId,a,b]);
    const category=await this.db.query(`SELECT COALESCE(c.name,'Uncategorized') name,SUM(e.total)::numeric amount FROM expense_management_records e LEFT JOIN expense_management_categories c ON c.id=e.category_id WHERE e.company_id=$1 AND e.expense_date BETWEEN $2 AND $3 AND e.status<>'rejected' GROUP BY c.name ORDER BY amount DESC LIMIT 8`,[companyId,a,b]);
    const branch=await this.db.query(`SELECT COALESCE(b.name,'Head Office') name,SUM(e.total)::numeric amount FROM expense_management_records e LEFT JOIN branches b ON b.id=e.branch_id WHERE e.company_id=$1 AND e.expense_date BETWEEN $2 AND $3 AND e.status<>'rejected' GROUP BY b.name ORDER BY amount DESC`,[companyId,a,b]);
    return {...summary.rows[0],by_category:category.rows,by_branch:branch.rows,from:a,to:b};
  }
  async findAll(companyId:string,q:any){const p:any[]=[companyId];const w=['e.company_id=$1'];for(const [key,col] of [['status','e.status'],['payment_status','e.payment_status'],['type','e.type'],['branch_id','e.branch_id'],['category_id','e.category_id']])if(q[key]){p.push(q[key]);w.push(`${col}=$${p.length}`)}if(q.from){p.push(q.from);w.push(`e.expense_date>=$${p.length}`)}if(q.to){p.push(q.to);w.push(`e.expense_date<=$${p.length}`)}if(q.search){p.push(`%${q.search}%`);w.push(`(e.expense_number ILIKE $${p.length} OR e.description ILIKE $${p.length} OR e.vendor ILIKE $${p.length} OR e.reference ILIKE $${p.length})`)}
    return (await this.db.query(`SELECT e.*,c.name category_name,b.name branch_name,s.name supplier_name,u.name created_by_name FROM expense_management_records e LEFT JOIN expense_management_categories c ON c.id=e.category_id LEFT JOIN branches b ON b.id=e.branch_id LEFT JOIN suppliers s ON s.id=e.supplier_id LEFT JOIN users u ON u.id=e.created_by WHERE ${w.join(' AND ')} ORDER BY e.expense_date DESC,e.created_at DESC LIMIT 500`,p)).rows;
  }
  async create(companyId:string,userId:string,b:any){const subtotal=Number(b.subtotal??b.amount),vat=Number(b.vat_amount||0),total=Number(b.total||subtotal+vat);if(!b.description||!b.expense_date||subtotal<0||total<=0)throw new BadRequestException('Description, date and valid amount are required');const id=randomUUID(),num=`EXP-${Date.now().toString().slice(-9)}`;const r=await this.db.query(`INSERT INTO expense_management_records(id,company_id,expense_number,type,category_id,branch_id,supplier_id,purchase_order_id,employee_name,vendor,description,expense_date,due_date,subtotal,vat_amount,total,payment_method,status,recurring_frequency,next_run_date,reference,receipt_url,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24) RETURNING *`,[id,companyId,num,b.type||'general',b.category_id||null,b.branch_id||null,b.supplier_id||null,b.purchase_order_id||null,b.employee_name||null,b.vendor||null,b.description,b.expense_date,b.due_date||null,subtotal,vat,total,b.payment_method||null,b.status==='pending'?'pending':'draft',b.recurring_frequency||null,b.next_run_date||null,b.reference||null,b.receipt_url||null,b.notes||null,userId]);await this.log(companyId,id,userId,'created');return r.rows[0];}
  async update(companyId:string,userId:string,id:string,b:any){const allowed=['type','category_id','branch_id','supplier_id','purchase_order_id','employee_name','vendor','description','expense_date','due_date','subtotal','vat_amount','total','payment_method','recurring_frequency','next_run_date','reference','receipt_url','notes'];const entries=Object.entries(b).filter(([k,v])=>allowed.includes(k)&&v!==undefined);if(!entries.length)throw new BadRequestException('No valid changes');const vals=entries.map(([,v])=>v===''?null:v),set=entries.map(([k],i)=>`${k}=$${i+3}`).join(',');const r=await this.db.query(`UPDATE expense_management_records SET ${set},updated_at=NOW() WHERE id=$1 AND company_id=$2 AND status IN('draft','rejected') RETURNING *`,[id,companyId,...vals]);if(!r.rows[0])throw new BadRequestException('Only draft or rejected expenses can be edited');await this.log(companyId,id,userId,'updated');return r.rows[0];}
  async transition(companyId:string,userId:string,id:string,status:string,comment?:string){const allowed:any={pending:['draft','rejected'],approved:['pending'],rejected:['pending']};const r=await this.db.query(`UPDATE expense_management_records SET status=$1,approved_by=CASE WHEN $1='approved' THEN $2 ELSE approved_by END,approved_at=CASE WHEN $1='approved' THEN NOW() ELSE approved_at END,updated_at=NOW() WHERE id=$3 AND company_id=$4 AND status=ANY($5::text[]) RETURNING *`,[status,userId,id,companyId,allowed[status]]);if(!r.rows[0])throw new BadRequestException(`Expense cannot be marked ${status}`);await this.log(companyId,id,userId,status,comment);return r.rows[0];}
  async pay(companyId:string,userId:string,id:string,b:any){return this.db.transaction(async c=>{const e=await c.query(`SELECT * FROM expense_management_records WHERE id=$1 AND company_id=$2 AND status='approved' FOR UPDATE`,[id,companyId]);if(!e.rows[0])throw new BadRequestException('Only approved expenses can be paid');const amount=Number(b.amount),due=Number(e.rows[0].total)-Number(e.rows[0].paid_amount);if(amount<=0||amount>due)throw new BadRequestException('Invalid payment amount');await c.query(`INSERT INTO expense_management_payments(id,company_id,expense_id,amount,method,reference,notes,paid_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[randomUUID(),companyId,id,amount,b.method||'bank_transfer',b.reference||null,b.notes||null,userId]);const paid=Number(e.rows[0].paid_amount)+amount,status=paid>=Number(e.rows[0].total)?'paid':'partial';const r=await c.query(`UPDATE expense_management_records SET paid_amount=$1,payment_status=$2,payment_method=$3,updated_at=NOW() WHERE id=$4 RETURNING *`,[paid,status,b.method||'bank_transfer',id]);await c.query(`INSERT INTO expense_management_activity(id,company_id,expense_id,action,comment,actor_id) VALUES($1,$2,$3,'payment',$4,$5)`,[randomUUID(),companyId,id,`${amount} via ${b.method||'bank_transfer'}`,userId]);return r.rows[0];});}
  async categories(companyId:string){return (await this.db.query(`SELECT c.*,COUNT(e.id)::int expense_count,COALESCE(SUM(e.total),0)::numeric actual FROM expense_management_categories c LEFT JOIN expense_management_records e ON e.category_id=c.id AND date_trunc('month',e.expense_date)=date_trunc('month',CURRENT_DATE) WHERE c.company_id=$1 AND c.active=true GROUP BY c.id ORDER BY c.name`,[companyId])).rows;}
  async createCategory(companyId:string,b:any){if(!b.name)throw new BadRequestException('Category name is required');return (await this.db.query(`INSERT INTO expense_management_categories(id,company_id,name,code,type,budget_monthly) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[randomUUID(),companyId,b.name,b.code||null,b.type||'operating',Number(b.budget_monthly||0)])).rows[0];}
  async supplierPayments(companyId:string){return (await this.db.query(`SELECT po.id,po.po_number,po.total,po.paid_amount,po.payment_status,po.due_date,po.status,s.id supplier_id,s.name supplier_name,(po.total-po.paid_amount)::numeric outstanding FROM purchase_orders po JOIN suppliers s ON s.id=po.supplier_id WHERE po.company_id=$1 AND po.status<>'cancelled' ORDER BY (po.payment_status<>'paid') DESC,po.due_date NULLS LAST`,[companyId])).rows;}
  async report(companyId:string,from?:string,to?:string){const [a,b]=this.dates(from,to);const rows=await this.db.query(`SELECT e.expense_number,e.expense_date,e.type,e.description,COALESCE(c.name,'Uncategorized') category,COALESCE(br.name,'Head Office') branch,e.vendor,e.status,e.payment_status,e.subtotal,e.vat_amount,e.total,e.paid_amount FROM expense_management_records e LEFT JOIN expense_management_categories c ON c.id=e.category_id LEFT JOIN branches br ON br.id=e.branch_id WHERE e.company_id=$1 AND e.expense_date BETWEEN $2 AND $3 ORDER BY e.expense_date DESC`,[companyId,a,b]);return {from:a,to:b,rows:rows.rows,total:rows.rows.reduce((s:any,x:any)=>s+Number(x.total),0),vat:rows.rows.reduce((s:any,x:any)=>s+Number(x.vat_amount),0)};}
  private async log(companyId:string,id:string,userId:string,action:string,comment?:string){await this.db.query(`INSERT INTO expense_management_activity(id,company_id,expense_id,action,comment,actor_id) VALUES($1,$2,$3,$4,$5,$6)`,[randomUUID(),companyId,id,action,comment||null,userId]);}
}
