import { storefrontApi } from '@/lib/api';

const titles:any={track:['Track Order','تتبع الطلب'],shipment:['Track Shipment','تتبع الشحنة'],returns:['Returns & Exchanges','الإرجاع والاستبدال'],faq:['Frequently Asked Questions','الأسئلة الشائعة'],contact:['Contact Us','اتصل بنا'],about:['About NuxStore','عن نوكس ستور'],careers:['Careers','الوظائف'],press:['Press & Media','الصحافة والإعلام'],blog:['Our Blog','مدونتنا'],stores:['Our Stores','متاجرنا'],privacy:['Privacy Policy','سياسة الخصوصية'],terms:['Terms & Conditions','الشروط والأحكام'],'shipping-policy':['Shipping Policy','سياسة الشحن'],cookies:['Cookie Policy','سياسة ملفات الارتباط'],accessibility:['Accessibility','إمكانية الوصول']};
const keys:any={returns:'returns',faq:'faq',about:'about',careers:'careers',press:'press',blog:'blog',stores:'stores',privacy:'privacy',terms:'terms','shipping-policy':'shipping_policy',cookies:'cookies',accessibility:'accessibility'};
export default async function InfoPage({params,searchParams}:{params:{locale:string;slug:string};searchParams?:{order_number?:string;phone?:string}}){
 const {locale,slug}=params;const ar=locale==='ar';let c:any={};try{c=await storefrontApi.getConfig()}catch{};let tracking:any=null;let trackingError='';if((slug==='track'||slug==='shipment')&&searchParams?.order_number&&searchParams?.phone){try{tracking=await storefrontApi.trackOrder(searchParams.order_number,searchParams.phone)}catch(e:any){trackingError=e?.response?.data?.message||'Order not found'}}const title=titles[slug]?.[ar?1:0]||slug;const key=keys[slug];const content=key?(c[`page_${key}${ar?'_ar':''}`]||c[`page_${key}`]):'';
 return <div className="max-w-4xl mx-auto px-4 py-14" dir={ar?'rtl':'ltr'}><div className="mb-8"><span className="text-gold-600 font-bold text-sm">NUXSTORE</span><h1 className="text-3xl md:text-4xl font-black mt-2">{title}</h1></div>
 {slug==='contact'?<div className="grid md:grid-cols-2 gap-6"><section className="bg-gray-50 rounded-2xl p-6 space-y-3"><h2 className="font-bold text-xl">{ar?'تواصل معنا':'Get in touch'}</h2><p>📞 {c.contact_phone||c.support_phone||'—'}</p><p>✉️ {c.contact_email||c.support_email||'—'}</p><p>📍 {ar?(c.contact_address_ar||c.contact_address):(c.contact_address||'Riyadh, Saudi Arabia')}</p><p>🕘 {c.contact_hours||'Saturday–Thursday, 9 AM–6 PM'}</p>{c.whatsapp_url&&<a className="inline-block bg-green-600 text-white rounded-full px-5 py-2" href={c.whatsapp_url}>WhatsApp</a>}</section><form className="border rounded-2xl p-6 space-y-4"><input className="w-full border rounded-xl p-3" placeholder={ar?'الاسم':'Name'}/><input className="w-full border rounded-xl p-3" placeholder={ar?'البريد الإلكتروني':'Email'}/><input className="w-full border rounded-xl p-3" placeholder={ar?'رقم الهاتف':'Phone'}/><textarea className="w-full border rounded-xl p-3 min-h-32" placeholder={ar?'كيف يمكننا مساعدتك؟':'How can we help?'}/><a href={`mailto:${c.contact_email||c.support_email||''}`} className="block text-center bg-luxury-900 text-white rounded-xl p-3 font-bold">{ar?'إرسال':'Send Message'}</a></form></div>:
 (slug==='track'||slug==='shipment')?<div className="bg-gray-50 rounded-2xl p-8"><p className="text-gray-600 mb-5">{ar?'أدخل رقم الطلب ورقم الهاتف للتحقق من الحالة.':'Enter your order number and phone number to check its status.'}</p><form className="grid md:grid-cols-2 gap-4"><input name="order_number" defaultValue={searchParams?.order_number} required className="border rounded-xl p-3" placeholder={ar?'رقم الطلب':'Order number'}/><input name="phone" defaultValue={searchParams?.phone} required className="border rounded-xl p-3" placeholder={ar?'رقم الهاتف':'Phone number'}/><button className="md:col-span-2 bg-luxury-900 text-white rounded-xl px-6 py-3 font-bold">{ar?'تتبع':'Track'}</button></form>{tracking&&<div className="mt-6 bg-white border rounded-xl p-5 grid grid-cols-2 gap-3"><span>{ar?'الطلب':'Order'}<b className="block">{tracking.order_number}</b></span><span>{ar?'الحالة':'Status'}<b className="block uppercase">{tracking.status}</b></span><span>{ar?'المنتجات':'Items'}<b className="block">{tracking.item_count}</b></span><span>{ar?'الإجمالي':'Total'}<b className="block">SAR {Number(tracking.total).toFixed(2)}</b></span></div>}{trackingError&&<p className="mt-4 text-red-600">{trackingError}</p>}</div>:
 <article className="prose max-w-none whitespace-pre-wrap text-gray-700 leading-8">{content|| (ar?'سيتم تحديث محتوى هذه الصفحة من لوحة الإدارة.':'This page content can be updated from the ERP E-commerce admin panel.')}</article>}</div>
}
