import { BadRequestException, ConflictException, Injectable, NotFoundException, OnModuleInit } from '@nestjs/common';
import { DatabaseService } from '../database/database.service';
import { randomUUID } from 'crypto';
import * as bcrypt from 'bcrypt';

const ROLE_TEMPLATES:any[]=[
 ['super_admin','Super Admin','Full system access.',['*']],['admin','Admin','Business operations, users and settings.',['dashboard.*','sales.*','inventory.*','purchasing.*','customers.*','finance.*','reports.*','users.*','settings.*','ecommerce.*','hr.*','payroll.*']],
 ['hr_manager','HR Manager','Employees, attendance, leave, payroll, documents and HR reports.',['hr.view','hr.dashboard','hr.employees.view','hr.employees.manage','hr.attendance.view','hr.attendance.manage','hr.shifts.view','hr.shifts.manage','hr.leaves.view','hr.leaves.apply','hr.leaves.approve','hr.payroll.view','hr.payroll.manage','hr.salary.view','hr.documents.view','hr.documents.manage','hr.requests.view','hr.requests.manage','hr.reports.view','hr.audit.view','payroll.view','payroll.manage']],
 ['branch_manager','Branch Manager','Branch employees, attendance and leave approvals.',['dashboard.view','sales.*','inventory.*','customers.*','approvals.*','reports.branch','hr.view','hr.employees.view','hr.attendance.view','hr.attendance.manage','hr.leaves.view','hr.leaves.approve','hr.requests.view']],['supervisor','Supervisor','Team supervision and limited approvals.',['dashboard.view','sales.*','inventory.view','customers.*','approvals.limited']],
 ['cashier','Cashier','Sales and customer transactions only.',['pos.*','sales.create','customers.create','customers.view']],['inventory_staff','Inventory Staff','Stock receiving, transfers and cycle counts.',['inventory.*','transfers.*','purchasing.receive']],
 ['warehouse_staff','Warehouse Staff','Warehouse operations.',['warehouses.*','inventory.view','inventory.adjust','transfers.*']],['ecommerce_staff','E-commerce Staff','Online orders, shipping and returns.',['ecommerce.*','orders.online.*','returns.*','customers.view']],
 ['customer_service','Customer Service','Customer accounts, returns and complaints.',['customers.*','returns.*','orders.view']],['accountant','Accountant','Finance, invoices, VAT and journals.',['finance.*','invoices.*','vat.*','reports.finance']],
 ['marketing','Marketing','Coupons, campaigns and promotions.',['marketing.*','loyalty.*','ecommerce.content','reports.marketing']],['auditor','Auditor','Read-only access to reports and logs.',['dashboard.view','reports.*','audit.view','hr.reports.view','hr.audit.view']],
 ['employee','Employee','Own profile, attendance, leave, payslip and HR requests.',['hr.self.view','hr.attendance.self','hr.leaves.apply','hr.payroll.self','hr.requests.submit','hr.documents.self']]
];

const DEFAULTS={
 business_name:'NuxFashion',business_name_ar:'نوكس فاشن',vat_number:'',cr_number:'',phone:'',email:'',address:'',address_ar:'',logo_url:'',currency:'SAR',timezone:'Asia/Riyadh',language:'en',
 vat_rate:15,prices_include_vat:true,zatca_enabled:true,simplified_invoice:true,invoice_prefix:'INV',invoice_footer:'Thank you for shopping with us',
 cash_enabled:true,mada_enabled:true,card_enabled:true,tabby_enabled:false,tamara_enabled:false,bank_transfer_enabled:true,cod_enabled:true,mada_commission:0,card_commission:0,tabby_commission:0,tamara_commission:0,
 negative_stock_allowed:true,require_customer:true,allow_split_payment:true,allow_discount:true,max_discount_percent:20,receipt_size:'80mm',auto_print_receipt:false,barcode_format:'CODE128',low_stock_threshold:5,
 store_enabled:true,default_delivery_fee:25,free_delivery_from:300,delivery_estimate:'2–5 business days',return_days:7,guest_checkout:true,online_stock_buffer:0,
 stock_transfer_approval:true,purchase_approval:true,expense_approval:true,email_notifications:true,low_stock_alerts:true,daily_sales_summary:true,audit_log_enabled:true,session_timeout_minutes:480,
 whatsapp_number:'',smtp_from_email:'',google_analytics_id:'',meta_pixel_id:'',webhook_url:''
};
const ALLOWED=new Set(Object.keys(DEFAULTS));
@Injectable()
export class SettingsService implements OnModuleInit{
 constructor(private db:DatabaseService){}
 async onModuleInit(){await this.db.query(`CREATE TABLE IF NOT EXISTS company_settings(company_id uuid PRIMARY KEY,settings jsonb NOT NULL DEFAULT '{}'::jsonb,updated_by uuid,updated_at timestamptz NOT NULL DEFAULT now())`);await this.db.query(`CREATE TABLE IF NOT EXISTS access_roles(id uuid PRIMARY KEY,company_id uuid NOT NULL,name varchar(100) NOT NULL,slug varchar(100) NOT NULL,description text,permissions jsonb NOT NULL DEFAULT '[]'::jsonb,is_system boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,slug))`);await this.db.query(`CREATE TABLE IF NOT EXISTS user_access_roles(user_id uuid NOT NULL,company_id uuid NOT NULL,role_id uuid NOT NULL REFERENCES access_roles(id) ON DELETE CASCADE,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(user_id,company_id,role_id))`)}
 async get(companyId:string){if(!companyId)throw new BadRequestException('Company is missing from login');const r=await this.db.query(`SELECT settings,updated_at FROM company_settings WHERE company_id=$1`,[companyId]);return {...DEFAULTS,...(r.rows[0]?.settings||{}),updated_at:r.rows[0]?.updated_at||null}}
 async update(companyId:string,userId:string,body:Record<string,unknown>){if(!companyId)throw new BadRequestException('Company is missing from login');const clean:any={};for(const [k,v] of Object.entries(body||{}))if(ALLOWED.has(k))clean[k]=v;if(Number(clean.vat_rate)<0||Number(clean.vat_rate)>100)throw new BadRequestException('VAT rate must be between 0 and 100');if(Number(clean.max_discount_percent)<0||Number(clean.max_discount_percent)>100)throw new BadRequestException('Maximum discount must be between 0 and 100');await this.db.query(`INSERT INTO company_settings(company_id,settings,updated_by) VALUES($1,$2::jsonb,$3) ON CONFLICT(company_id) DO UPDATE SET settings=company_settings.settings||EXCLUDED.settings,updated_by=EXCLUDED.updated_by,updated_at=now()`,[companyId,JSON.stringify(clean),userId]);return this.get(companyId)}
 private async seedRoles(companyId:string){for(const [slug,name,description,permissions] of ROLE_TEMPLATES)await this.db.query(`INSERT INTO access_roles(id,company_id,name,slug,description,permissions) VALUES($1,$2,$3,$4,$5,$6::jsonb) ON CONFLICT(company_id,slug) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description`,[randomUUID(),companyId,name,slug,description,JSON.stringify(permissions)])}
 async roles(companyId:string){await this.seedRoles(companyId);return (await this.db.query(`SELECT * FROM access_roles WHERE company_id=$1 ORDER BY CASE slug WHEN 'super_admin' THEN 1 WHEN 'admin' THEN 2 ELSE 3 END,name`,[companyId])).rows}
 async updateRole(companyId:string,id:string,permissions:string[]){const r=await this.db.query(`UPDATE access_roles SET permissions=$1::jsonb WHERE id=$2 AND company_id=$3 RETURNING *`,[JSON.stringify(permissions||[]),id,companyId]);if(!r.rows[0])throw new NotFoundException('Role not found');return r.rows[0]}
 async users(companyId:string){await this.seedRoles(companyId);return (await this.db.query(`SELECT u.id,u.name,u.email,u.is_active,u.last_login_at,COALESCE(json_agg(json_build_object('id',ar.id,'name',ar.name,'slug',ar.slug)) FILTER(WHERE ar.id IS NOT NULL),'[]') roles FROM users u JOIN user_company_roles ucr ON ucr.user_id=u.id AND ucr.company_id=$1 LEFT JOIN user_access_roles uar ON uar.user_id=u.id AND uar.company_id=$1 LEFT JOIN access_roles ar ON ar.id=uar.role_id WHERE u.deleted_at IS NULL GROUP BY u.id ORDER BY u.name,u.email`,[companyId])).rows}
 async createUser(companyId:string,body:any){const email=String(body.email||'').trim().toLowerCase(),name=String(body.name||'').trim(),password=String(body.password||'');if(!name||!email.includes('@'))throw new BadRequestException('Name and valid email are required');if(password.length<8)throw new BadRequestException('Password must contain at least 8 characters');if((await this.db.query(`SELECT 1 FROM users WHERE LOWER(email)=LOWER($1) AND deleted_at IS NULL`,[email])).rows[0])throw new ConflictException('Email already exists');const roleIds=Array.isArray(body.role_ids)?body.role_ids:[];if(!roleIds.length)throw new BadRequestException('Assign at least one role');const valid=await this.db.query(`SELECT id,slug FROM access_roles WHERE company_id=$1 AND id=ANY($2::uuid[])`,[companyId,roleIds]);if(!valid.rows.length)throw new BadRequestException('Invalid roles');const legacy=await this.db.query(`SELECT id FROM roles ORDER BY CASE WHEN LOWER(name) IN ('admin','administrator','super admin') THEN 0 ELSE 1 END LIMIT 1`);if(!legacy.rows[0])throw new BadRequestException('No system role exists');const id=randomUUID(),hash=await bcrypt.hash(password,12);return this.db.transaction(async c=>{const u=await c.query(`INSERT INTO users(id,email,name,password_hash,is_active) VALUES($1,$2,$3,$4,$5) RETURNING id,name,email,is_active`,[id,email,name,hash,body.is_active!==false]);await c.query(`INSERT INTO user_company_roles(user_id,company_id,role_id) VALUES($1,$2,$3)`,[id,companyId,legacy.rows[0].id]);for(const role of valid.rows)await c.query(`INSERT INTO user_access_roles(user_id,company_id,role_id) VALUES($1,$2,$3)`,[id,companyId,role.id]);return {...u.rows[0],roles:valid.rows}})}
 async updateUser(companyId:string,id:string,body:any){if(id===body.current_user_id&&body.is_active===false)throw new BadRequestException('You cannot deactivate your own account');const owned=await this.db.query(`SELECT u.id FROM users u JOIN user_company_roles r ON r.user_id=u.id WHERE u.id=$1 AND r.company_id=$2`,[id,companyId]);if(!owned.rows[0])throw new NotFoundException('User not found');await this.db.transaction(async c=>{await c.query(`UPDATE users SET name=COALESCE($1,name),is_active=COALESCE($2,is_active) WHERE id=$3`,[body.name||null,body.is_active,id]);if(Array.isArray(body.role_ids)){await c.query(`DELETE FROM user_access_roles WHERE user_id=$1 AND company_id=$2`,[id,companyId]);for(const roleId of body.role_ids)await c.query(`INSERT INTO user_access_roles(user_id,company_id,role_id) SELECT $1,$2,id FROM access_roles WHERE id=$3 AND company_id=$2`,[id,companyId,roleId])}});return {success:true}}
 async changePassword(companyId:string,id:string,password:string){if(String(password||'').length<8)throw new BadRequestException('Password must contain at least 8 characters');const owned=await this.db.query(`SELECT u.id FROM users u JOIN user_company_roles r ON r.user_id=u.id WHERE u.id=$1 AND r.company_id=$2`,[id,companyId]);if(!owned.rows[0])throw new NotFoundException('User not found');await this.db.query(`UPDATE users SET password_hash=$1,failed_login_attempts=0,locked_until=NULL WHERE id=$2`,[await bcrypt.hash(password,12),id]);return{success:true}}
}
