import { useState } from 'react';
import type { CSSProperties,FormEvent } from 'react';
import { useAuth } from '../context/AuthContext';

export default function Login({portal='admin',onLogin}:{portal?:'admin'|'pos';onLogin:(p:'admin'|'pos')=>void}){
  const {login}=useAuth();const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[showPassword,setShowPassword]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  const isPos=portal==='pos',bannerUrl=import.meta.env.VITE_LOGIN_BANNER_URL||'/login-banner.jpg',bannerStyle={'--login-banner':`url("${bannerUrl}")`} as CSSProperties;
  const submit=async(e:FormEvent)=>{e.preventDefault();setError('');setLoading(true);try{await login(email,password,portal);onLogin(portal)}catch(err:any){setError(err?.response?.data?.message||`Unable to sign in to the ${isPos?'POS':'admin'} portal.`)}finally{setLoading(false)}};
  return <main className="login-shell">
    <section className="login-banner" style={bannerStyle}><div className="login-banner-top"><div className="login-mark"><i className="ti ti-hanger-2"/></div><div><strong>NuxFashion</strong><span>{isPos?'Branch Point of Sale':'Retail Management'}</span></div></div><div className="login-banner-copy"><div className="login-eyebrow">{isPos?'Secure branch checkout':'Fashion retail, simplified'}</div><h1>{isPos?'Sell faster. Serve better.':<>Manage every sale.<br/>Grow every branch.</>}</h1><p>{isPos?'Sign in with the account assigned to this branch. Sales and shifts will be recorded against your branch.':'A complete ERP workspace designed for modern Saudi fashion retailers.'}</p><div className="login-features"><span><i className="ti ti-circle-check-filled"/> ZATCA Ready</span><span><i className="ti ti-circle-check-filled"/> Branch Controlled</span><span><i className="ti ti-circle-check-filled"/> Live Inventory</span></div></div><div className="login-banner-foot">NuxFashion ERP & POS <span>•</span> Saudi Arabia</div></section>
    <section className="login-side"><div className="login-mobile-brand"><div className="login-mark"><i className="ti ti-hanger-2"/></div><div><strong>NuxFashion</strong><span>{isPos?'Branch POS':'ERP Admin'}</span></div></div><div className="login-card"><div className="login-heading"><div className="login-secure"><i className={`ti ${isPos?'ti-device-desktop':'ti-shield-check'}`}/> {isPos?'Branch POS access':'Administrator access'}</div><h2>{isPos?'Open your POS':'Welcome back'}</h2><p>{isPos?'Use the email and password assigned by your administrator.':'Sign in to manage your complete business.'}</p></div>
      {error&&<div className="login-error"><i className="ti ti-alert-circle"/><span>{error}</span></div>}<form onSubmit={submit} className="login-form"><label><span>Email address</span><div className="login-input"><i className="ti ti-mail"/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder={isPos?'cashier@branch.com':'admin@company.com'} autoComplete="email" required autoFocus/></div></label><label><span>Password</span><div className="login-input"><i className="ti ti-lock"/><input type={showPassword?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" autoComplete="current-password" required/><button type="button" onClick={()=>setShowPassword(v=>!v)} aria-label={showPassword?'Hide password':'Show password'}><i className={`ti ${showPassword?'ti-eye-off':'ti-eye'}`}/></button></div></label><button type="submit" className="login-submit" disabled={loading}>{loading?<><i className="ti ti-loader-2 login-spin"/> Signing in…</>:<>{isPos?'Open Branch POS':'Open Admin Panel'} <i className="ti ti-arrow-right"/></>}</button></form>
      <a className="login-store-link" href={isPos?'/':'/pos-login'}><i className={`ti ${isPos?'ti-shield-lock':'ti-device-desktop'}`}/> {isPos?'Administrator login':'Branch POS login'}</a><div className="login-help"><i className="ti ti-headset"/> Need help? Contact your system administrator.</div></div><div className="login-side-foot">© {new Date().getFullYear()} NuxFashion <span>Privacy</span><span>Support</span></div></section>
  </main>;
}
